# SBERT Sentence Analysis

## 1. Preparations

### 1.1 Read Data
The sentence data were preprocessed (see preprocessing.ipynb)
In the dataframe:  
- "sentence" = preprocessed sentences with placeholders of anonymized information, **used for the analysis**
- "clean_sentence" = proprocessed sentences with placeholders removed,  
- "translated_sentence" = translated from "sentence" column to English with translate.ipynb

In [1]:
# first install numpy=1.26.4 before installing pandas and other packages
%pip install numpy==1.26.4
%pip install pandas openpyxl

import pandas as pd
# read the sentence data 
df = pd.read_excel("..\\..\\data\\sentence_data_for_analysis.xlsx", index_col=0)
sentences = df["sentence"].to_list()

# check the df head
df.head()

Collecting numpy==1.26.4
  Using cached numpy-1.26.4-cp310-cp310-win_amd64.whl.metadata (61 kB)
Using cached numpy-1.26.4-cp310-cp310-win_amd64.whl (15.8 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.2.6
    Uninstalling numpy-2.2.6:
      Successfully uninstalled numpy-2.2.6
Successfully installed numpy-1.26.4
Note: you may need to restart the kernel to use updated packages.

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\p70092940\OneDrive - Maastricht University\Desktop\Projects\MyIBDcoach-NLP\mijnidbcoachnlp\.venv\Lib\site-packages\~umpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\p70092940\OneDrive - Maastricht University\Desktop\Projects\MyIBDcoach-NLP\mijnidbcoachnlp\.venv\Lib\site-packages\~umpy'.
  You can safely remove it manually.

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (2.3.1)
Requirement already satisfied: openpyxl in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (3.1.5)
Requirement already satisfied: numpy>=1.22.4 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: et-xmlfile in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

,message_id,sentence,clean_sentence,sentence_id,translated_sentence
0,1,"Geachte ibd groep, Is mijn uitslag al binnen ...","ibd groep, Is mijn uitslag al binnen van de b...",1,"Dear Ibd group, has my results come back from ..."
1,3,Vorige week is door [ZIEKENHUIS] [LOCATIE] mij...,Vorige week is door mijn ontlasting onderzoc...,2,Last week my stool was examined by [SIGHSHOUSE...
2,3,Graag zou ik de uitkomst hiervan vernemen.,Graag zou ik de uitkomst hiervan vernemen.,3,I would like to hear the outcome of this.
3,4,bloed in de ontlasting wordt steeds meer en st...,bloed in de ontlasting wordt steeds meer en st...,4,blood in the stool is becoming more and more f...
4,4,Ligt dit aan de medicatie?,Ligt dit aan de medicatie?,5,Is this because of the medication?

In [2]:
# check input size
len_data = len(sentences)
print(f"data size: {len_data}")

data size: 41119

In [3]:
### Importing the list of Dutch stopwords (note that there are customized dutch words in there)

with open('..\\..\\data\\stopwords-nl.txt', 'r') as file:
    lines = [line.strip() for line in file.readlines()]

dutch_stopwords = lines

In [2]:
%pip install gensim

import pickle
from gensim.corpora import Dictionary

# Load the tokenized texts
with open("..\\..\\data\\tokens\\tokenized_sentences.pkl", "rb") as f:
    tokenized_texts = pickle.load(f)

dictionary = Dictionary(tokenized_texts)

Requirement already satisfied: gensim in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (4.3.3)
Requirement already satisfied: numpy<2.0,>=1.18.5 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from gensim) (1.26.4)
Requirement already satisfied: scipy<1.14.0,>=1.7.0 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from gensim) (1.13.1)
Requirement already satisfied: smart-open>=1.8.1 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from gensim) (7.3.0.post1)
Requirement already satisfied: wrapt in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from smart-open>=1.8.1->gensim) (1.17.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

### 1.2 Embed the lists of sentences (Commented Out)
In this section, we embed the sentence data with five differen sentence transformer models available on Hugging Face. Only run once.

In [5]:
%pip install sentence_transformers

from sentence_transformers import SentenceTransformer
from tqdm.autonotebook import tqdm  
import numpy as np
import sentence_transformers.util
import os 
import numpy as np

def embed_and_save(docs, embedding_model, save_path):
    """Generate embeddings for documents and save them with model name in the filename."""
    embeddings = embedding_model.encode(docs, show_progress_bar=True)
    
    # Use model class name as identifier
    model_name = embedding_model.__class__.__name__
    
    # Create the full file path
    file_name = f'embeddings_{model_name}.npy'
    file_path = os.path.join(save_path, file_name)
    
    # Save the embeddings
    np.save(file_path, embeddings)

    # print saved embeddings
    print(f"Embedding saved successfully to {file_path}")

Requirement already satisfied: sentence_transformers in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (5.0.0)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from sentence_transformers) (4.53.3)
Requirement already satisfied: tqdm in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from sentence_transformers) (4.67.1)
Requirement already satisfied: torch>=1.11.0 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from sentence_transformers) (2.7.1)
Requirement already satisfied: scikit-learn in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from sentence_transformers) (1.7.1)
Requirement already satisfied: scipy in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from sentence_transformers) (1.13.1)
Requirement already satisfied: huggingface-hub>=0.20.0 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from sentence_transformers) (0.33.4)
Requirement already satisfied: Pillow in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from sentence_transformers) (11.3.0)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from sentence_transformers) (4.14.1)
Requirement already satisfied: filelock in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence_transformers) (3.18.0)
Requirement already satisfied: numpy>=1.17 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence_transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence_transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence_transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence_transformers) (2024.11.6)
Requirement already satisfied: requests in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence_transformers) (2.32.4)
Requirement already satisfied: tokenizers<0.22,>=0.21 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence_transformers) (0.21.2)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence_transformers) (0.5.3)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from huggingface-hub>=0.20.0->sentence_transformers) (2025.7.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from torch>=1.11.0->sentence_transformers) (1.14.0)
Requirement already satisfied: networkx in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from torch>=1.11.0->sentence_transformers) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from torch>=1.11.0->sentence_transformers) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence_transformers) (1.3.0)
Requirement already satisfied: colorama in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from tqdm->sentence_transformers) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from jinja2->torch>=1.11.0->sentence_transformers) (3.0.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence_transformers) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence_transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence_transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence_transformers) (2025.7.14)
Requirement already satisfied: joblib>=1.2.0 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from scikit-learn->sentence_transformers) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from scikit-learn->sentence_transformers) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution -cipy (c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages)
WARNING: Ignoring invalid distribution -cipy (c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages)
WARNING: Ignoring invalid distribution -cipy (c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages)

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip
c:\Users\p70092940\OneDrive - Maastricht University\Desktop\Projects\MyIBDcoach-NLP\mijnidbcoachnlp\.venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [6]:
# list of all embedding models to try out
from sentence_transformers import SentenceTransformer

embedding_models = [
    #("stv1", SentenceTransformer("distiluse-base-multilingual-cased-v1")),
    #("stv2", SentenceTransformer("distiluse-base-multilingual-cased-v2")),
    #("mini", SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")),
    #("mpnet", SentenceTransformer("paraphrase-multilingual-mpnet-base-v2")),
    #("robbert", SentenceTransformer("NetherlandsForensicInstitute/robbert-2022-dutch-sentence-transformers")),
    #("e5", SentenceTransformer("intfloat/multilingual-e5-large-instruct", trust_remote_code=True))
    ("qwen3", SentenceTransformer("Qwen/Qwen3-Embedding-8B"))

]

Loading checkpoint shards: 100%|██████████| 4/4 [00:06<00:00,  1.50s/it]

In [9]:
# embed the documents with all embedding models

#for (name, embedding_model) in embedding_models:
    #save_path = "/workspace/persistent/mijnidbcoachnlp/data/embeddings_full_docs"
    # embed all the sentences
    #embed_and_save(docs=sentences, embedding_model=embedding_model, save_path=save_path)
    #print("All embeddings saved successfully.")

### 1.3 Load embeddings

In [ ]:
import numpy as np
from sentence_transformers import SentenceTransformer
#%pip install hf_xet
# Define model names and embeddings
models_and_embeddings = [
    #("stv1", SentenceTransformer("distiluse-base-multilingual-cased-v1"), np.load("/workspace/persistent/mijnidbcoachnlp/data/embeddings_full_docs/embeddings_st_v1_sentence_placeholder.npy")),
    #("stv2", SentenceTransformer("distiluse-base-multilingual-cased-v2"), np.load("/workspace/persistent/mijnidbcoachnlp/data/embeddings_full_docs/embeddings_st_v2_sentence_placeholder.npy")),
    #("mini", SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2"), np.load("/workspace/persistent/mijnidbcoachnlp/data/embeddings_full_docs/embeddings_st_miniL12v2_sentence_placeholder.npy")),
    ("mpnet", SentenceTransformer("paraphrase-multilingual-mpnet-base-v2"), np.load("..\\..\\data\\embeddings_st_mpnet_v2_sentence_placeholder.npy")),
    ("robbert", SentenceTransformer("NetherlandsForensicInstitute/robbert-2022-dutch-sentence-transformers"), np.load("..\\..\\data\\embeddings_st_robbert2022_sentence_placeholder.npy")),
    ("qwen3", SentenceTransformer("Qwen/Qwen3-Embedding-8B"), np.load("..\\..\\data\\embeddings_qwen3.npy"))
    #("e5", SentenceTransformer("intfloat/multilingual-e5-large-instruct", trust_remote_code=True), np.load("/workspace/persistent/mijnidbcoachnlp/data/embeddings_full_docs/embeddings_e5.npy"))
]

c:\Users\p70092940\OneDrive - Maastricht University\Desktop\Projects\MyIBDcoach-NLP\mijnidbcoachnlp\.venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

In [11]:
models_and_embeddings_dict = {
    name: (model, embedding)
    for name, model, embedding in models_and_embeddings
}

In [12]:
# disable parallelism to avoid some warnings
import os
os.environ["TOKENIZERS_PARALLELISM"] = "false"

#### 1.4. Initializa BERTopic settings

In [13]:
%pip install umap-learn hdbscan 

from umap import UMAP
from hdbscan import HDBSCAN
from sklearn.feature_extraction.text import CountVectorizer

# Shared settings with multiple representation models
bertopic_settings = {
    "vectorizer_model": CountVectorizer(stop_words=dutch_stopwords, min_df=2, ngram_range=(1, 1), token_pattern=r'\b[a-zA-Z]{3,}\b'),
    "calculate_probabilities": False,
    "verbose": False
    #"representation_model": {
        #"Default": "default",  # This uses the default c-TF-IDF representation
        #"KeyBERTInspired": KeyBERTInspired()
    #}
}

Requirement already satisfied: umap-learn in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (0.5.9.post2)
Requirement already satisfied: hdbscan in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (0.8.40)
Requirement already satisfied: numpy>=1.23 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from umap-learn) (1.26.4)
Requirement already satisfied: scipy>=1.3.1 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from umap-learn) (1.12.0)
Requirement already satisfied: scikit-learn>=1.6 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from umap-learn) (1.7.0)
Requirement already satisfied: numba>=0.51.2 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from umap-learn) (0.61.2)
Requirement already satisfied: pynndescent>=0.5 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from umap-learn) (0.5.13)
Requirement already satisfied: tqdm in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from umap-learn) (4.67.1)
Requirement already satisfied: joblib>=1.0 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from hdbscan) (1.5.1)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from numba>=0.51.2->umap-learn) (0.44.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from scikit-learn>=1.6->umap-learn) (3.6.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Note: you may need to restart the kernel to use updated packages.

## 3. Coarse Grid Search

### 3.1 Preparations for grid search

In [14]:
# function to return top n words 
# function to get top words
from typing import List

def get_top_words(topic_model, top_n: int) -> List[List[str]]:
    """Extract top words for each topic from BERTopic (excluding outliers and empty words)."""
    topics = topic_model.get_topics()  # topics is a dict: {topic_num: [(word, score), ...]}
    top_words = []
    for topic_num, word_score_list in topics.items():
        if topic_num == -1:
            continue  # Skip outlier topic (-1)
        words = [word for word, _ in word_score_list[:top_n] if word.strip()]  # Skip empty words
        if words:  # Only append if the words list is not empty
            top_words.append(words)
    return top_words

In [15]:
%pip install octis

# functions for diversity, number of topics and coherence
from octis.evaluation_metrics.diversity_metrics import TopicDiversity
from collections import defaultdict
from typing import List

# function to evaluate topic diversity
def get_topic_diversity(top_words, topk=10):
    metric = TopicDiversity(topk=topk)
    diversity_score = metric.score({"topics": top_words}) 
    return diversity_score

# function to calculate coverage
def get_coverage(topic_model):
    """Calculate the proportion of documents assigned to valid topics (topic != -1)."""
    topics = topic_model.topics_
    valid_topic_count = sum(1 for topic in topics if topic != -1)
    return valid_topic_count / len(topics)

def get_nr_topics(topic_model):
    topic_info = topic_model.get_topic_info()
    # Exclude the outlier class (-1) if you want only real topics
    nr_topics = topic_info[topic_info.Topic != -1].shape[0]
    return nr_topics

from gensim.corpora import Dictionary
from gensim.models.coherencemodel import CoherenceModel

def get_c_v(topic_model, tokenized_texts, dictionary, top_words):
    
    # Prepare CoherenceModel
    coherence_model = CoherenceModel(
        topics=top_words,
        texts=tokenized_texts,
        dictionary=dictionary,
        coherence='c_v'
    )
    
    # Compute coherence
    coherence_score = coherence_model.get_coherence()
    
    return coherence_score

Requirement already satisfied: octis in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (1.14.0)
Requirement already satisfied: gensim<5.0,>=4.2.0 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from octis) (4.3.3)
Requirement already satisfied: nltk in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from octis) (3.9.1)
Requirement already satisfied: pandas in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from octis) (2.3.1)
Requirement already satisfied: spacy in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from octis) (3.8.7)
Collecting scikit-learn==1.1.0 (from octis)
  Using cached scikit_learn-1.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (10 kB)
Requirement already satisfied: scikit-optimize>=0.8.1 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from octis) (0.10.2)
Requirement already satisfied: matplotlib in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from octis) (3.10.3)
Requirement already satisfied: torch in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from octis) (2.7.1)
Requirement already satisfied: numpy<2.0,>=1.23.0 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from octis) (1.26.4)
Requirement already satisfied: libsvm in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from octis) (3.23.0.4)
Requirement already satisfied: flask in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from octis) (3.1.1)
Requirement already satisfied: sentence-transformers in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from octis) (5.0.0)
Requirement already satisfied: requests in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from octis) (2.32.4)
Requirement already satisfied: tomotopy in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from octis) (0.13.0)
Requirement already satisfied: scipy<1.13 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from octis) (1.12.0)
Requirement already satisfied: joblib>=1.0.0 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from scikit-learn==1.1.0->octis) (1.5.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from scikit-learn==1.1.0->octis) (3.6.0)
Requirement already satisfied: smart-open>=1.8.1 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from gensim<5.0,>=4.2.0->octis) (7.3.0.post1)
Requirement already satisfied: pyaml>=16.9 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from scikit-optimize>=0.8.1->octis) (25.5.0)
Requirement already satisfied: packaging>=21.3 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from scikit-optimize>=0.8.1->octis) (25.0)
Requirement already satisfied: PyYAML in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from pyaml>=16.9->scikit-optimize>=0.8.1->octis) (6.0.2)
Requirement already satisfied: wrapt in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from smart-open>=1.8.1->gensim<5.0,>=4.2.0->octis) (1.17.2)
Requirement already satisfied: blinker>=1.9.0 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from flask->octis) (1.9.0)
Requirement already satisfied: click>=8.1.3 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from flask->octis) (8.2.1)
Requirement already satisfied: itsdangerous>=2.2.0 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from flask->octis) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from flask->octis) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from flask->octis) (3.0.2)
Requirement already satisfied: werkzeug>=3.1.0 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from flask->octis) (3.1.3)
Requirement already satisfied: contourpy>=1.0.1 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from matplotlib->octis) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from matplotlib->octis) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from matplotlib->octis) (4.58.5)
Requirement already satisfied: kiwisolver>=1.3.1 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from matplotlib->octis) (1.4.8)
Requirement already satisfied: pillow>=8 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from matplotlib->octis) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from matplotlib->octis) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from matplotlib->octis) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib->octis) (1.17.0)
Requirement already satisfied: regex>=2021.8.3 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from nltk->octis) (2024.11.6)
Requirement already satisfied: tqdm in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from nltk->octis) (4.67.1)
Requirement already satisfied: pytz>=2020.1 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from pandas->octis) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from pandas->octis) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from requests->octis) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from requests->octis) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from requests->octis) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from requests->octis) (2025.7.9)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from sentence-transformers->octis) (4.53.1)
Requirement already satisfied: huggingface-hub>=0.20.0 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from sentence-transformers->octis) (0.33.2)
Requirement already satisfied: typing_extensions>=4.5.0 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from sentence-transformers->octis) (4.14.1)
Requirement already satisfied: filelock in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers->octis) (3.18.0)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers->octis) (0.21.2)
Requirement already satisfied: safetensors>=0.4.3 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers->octis) (0.5.3)
Requirement already satisfied: fsspec>=2023.5.0 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from huggingface-hub>=0.20.0->sentence-transformers->octis) (2025.5.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from huggingface-hub>=0.20.0->sentence-transformers->octis) (1.1.5)
Requirement already satisfied: sympy>=1.13.3 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from torch->octis) (1.14.0)
Requirement already satisfied: networkx in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from torch->octis) (3.4.2)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from torch->octis) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from torch->octis) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from torch->octis) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.5.1.17 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from torch->octis) (9.5.1.17)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from torch->octis) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from torch->octis) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from torch->octis) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from torch->octis) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from torch->octis) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.3 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from torch->octis) (0.6.3)
Requirement already satisfied: nvidia-nccl-cu12==2.26.2 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from torch->octis) (2.26.2)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from torch->octis) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from torch->octis) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from torch->octis) (1.11.1.6)
Requirement already satisfied: triton==3.3.1 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from torch->octis) (3.3.1)
Requirement already satisfied: setuptools>=40.8.0 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from triton==3.3.1->torch->octis) (78.1.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from sympy>=1.13.3->torch->octis) (1.3.0)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from spacy->octis) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from spacy->octis) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from spacy->octis) (1.0.13)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from spacy->octis) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from spacy->octis) (3.0.10)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from spacy->octis) (8.3.4)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from spacy->octis) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from spacy->octis) (2.5.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from spacy->octis) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from spacy->octis) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from spacy->octis) (0.16.0)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from spacy->octis) (2.11.7)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from spacy->octis) (3.5.0)
Requirement already satisfied: language-data>=1.2 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from langcodes<4.0.0,>=3.2.0->spacy->octis) (1.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy->octis) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy->octis) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy->octis) (0.4.1)
Requirement already satisfied: blis<1.3.0,>=1.2.0 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from thinc<8.4.0,>=8.3.4->spacy->octis) (1.2.1)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from thinc<8.4.0,>=8.3.4->spacy->octis) (0.1.5)
Requirement already satisfied: shellingham>=1.3.0 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from typer<1.0.0,>=0.3.0->spacy->octis) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from typer<1.0.0,>=0.3.0->spacy->octis) (14.0.0)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from weasel<0.5.0,>=0.1.0->spacy->octis) (0.21.1)
Requirement already satisfied: marisa-trie>=1.1.0 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy->octis) (1.2.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy->octis) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy->octis) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /root/anaconda3/envs/myenv/lib/python3.10/site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy->octis) (0.1.2)
Using cached scikit_learn-1.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (30.7 MB)
Installing collected packages: scikit-learn
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.7.0
    Uninstalling scikit-learn-1.7.0:
      Successfully uninstalled scikit-learn-1.7.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
umap-learn 0.5.9.post2 requires scikit-learn>=1.6, but you have scikit-learn 1.1.0 which is incompatible.
Successfully installed scikit-learn-1.1.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Note: you may need to restart the kernel to use updated packages.

In [16]:
# functions to calculate embedding coherence
from typing import List, Tuple, Dict
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

def cluster_coherence(embeddings: np.ndarray) -> float:
    """
    Compute the average pairwise cosine similarity among embeddings.
    If only one item in cluster, returns NaN.
    """
    n = embeddings.shape[0]
    if n < 2:
        return np.nan
    sim_mat = cosine_similarity(embeddings)
    iu = np.triu_indices(n, k=1)
    return sim_mat[iu].mean()

def get_intra_topic_similarity(
    topic_model, 
    sentences: List[str], 
    embeddings: np.ndarray
) -> Tuple[float, float, Dict[int, float]]:
    document_info = topic_model.get_document_info(sentences)
    clusters = document_info['Topic'].to_list()

    df = pd.DataFrame({
        'sentence': sentences,
        'embedding': list(embeddings),
        'cluster': clusters
    })

    total_weighted_sim = 0.0
    total_docs = 0
    similarities = []

    for cluster_label, group in df.groupby('cluster'):
        if cluster_label == -1:
            continue  # Skip outlier topic

        embs = np.vstack(group['embedding'].values)
        mean_sim = cluster_coherence(embs)
        cluster_size = len(group)

        if not np.isnan(mean_sim):
            similarities.append(mean_sim)

            total_weighted_sim += mean_sim * cluster_size
            total_docs += cluster_size

    # Compute weighted and unweighted averages
    weighted_mean_sim = total_weighted_sim / total_docs if total_docs > 0 else np.nan
    unweighted_mean_sim = np.mean(similarities) if similarities else np.nan

    return weighted_mean_sim, unweighted_mean_sim

In [18]:
# initialize the range of parameters for coarse grid search

min_cluster_sizes = [10, 20, 30, 40]
range_n_components = [5, 10, 15]
range_n_neighbors = [10, 20, 30, 40]

from itertools import product

# Generate all combinations
coarse_param_combinations = list(product(
    min_cluster_sizes, 
    range_n_components,
    range_n_neighbors, 
))

print(f"Total combinations of coarse grid search for each model: {len(coarse_param_combinations)}")

Total combinations of coarse grid search for each model: 48

In [19]:
# initialize the range of parameters for coarse grid search

min_cluster_sizes = [10, 15, 20, 25, 30, 35, 40]
range_n_components = [5, 7, 10, 15]
range_n_neighbors = [10, 20, 30, 40]

from itertools import product

# Generate all combinations
all_param_combinations = list(product(
    min_cluster_sizes, 
    range_n_components,
    range_n_neighbors, 
))

untried_param_combos = [x for x in all_param_combinations if x not in coarse_param_combinations]


print(f"Total combinations of coarse grid search for each model: {len(untried_param_combos)}")

Total combinations of coarse grid search for each model: 64

### 3.1 Coarse search

In [ ]:
# scikit-learn must be upgraded here to avoid dependency conflic
#%pip install -upgrade scikit-learn
#%pip install bertopic

from umap import UMAP
from hdbscan import HDBSCAN
from sklearn.feature_extraction.text import CountVectorizer
from bertopic import BERTopic

# function for grid search
def coarse_grid_search(docs, models_and_embeddings, param_combinations, tokenized_texts, dictionary, save_path):

    metrics_vs_combination = defaultdict(dict)

    for name, embedding_model, embeddings in models_and_embeddings:
        metrics_results_model = defaultdict(dict)

        for combination in param_combinations:
        # access the three params
            min_cluster_size, n_components, n_neighbors = combination
            
            # initialize a topic model with the basic setting
            topic_model = BERTopic(**bertopic_settings)
            
            # update the hdbscan model and umap model with the three parameters
            topic_model.hdbscan_model = HDBSCAN(min_cluster_size=min_cluster_size, metric='euclidean', cluster_selection_method='eom', prediction_data=False)
            topic_model.umap_model = UMAP(n_neighbors=n_neighbors, n_components=n_components, min_dist=0.0, metric='cosine', random_state=42)
            print(f"Tuning model: {name} at param combination: min_cluster_size = {min_cluster_size}, n_components = {n_components}, n_neighbors = {n_neighbors}")

            topics, probs = topic_model.fit_transform(docs, embeddings)


            coverage = get_coverage(topic_model)
            nr_topics = get_nr_topics(topic_model)
            
            print(f"Document: {coverage}")
            print(f"Number of topics: {nr_topics}")


            #min_topic_threshold = len(docs) // 200 # min number of topics is set at 200 docs per topic
            
            top_words = get_top_words(topic_model, top_n=10)
            try:
                diversity_score = get_topic_diversity(top_words)
                print(f"Diversity score: {diversity_score}")
            
                c_v_score = get_c_v(topic_model, tokenized_texts, dictionary, top_words)
                print(f"C_V coherence: {c_v_score}")
            except Exception:
                c_v_score = None
                diversity_score = None
                print("Exception Error")

            weighted_sim, unweighted_sim = get_intra_topic_similarity(
                topic_model, docs, embeddings
            )
            print(f"Average embedding cosine similarity weighted: {weighted_sim}, unweighted: {unweighted_sim}")
            print(" ")
            # ... [same as before]
            metrics_results_model[combination] = {
                "min_cluster_size": min_cluster_size,
                "n_components": n_components,
                "n_neighbors": n_neighbors,
                "diversity_score": diversity_score,
                "c_v_score": c_v_score,
                "weighted_avg_sim": weighted_sim,
                "unweighted_avg_sim": unweighted_sim,
                "document_coverage": coverage,
                "number_of_topics": nr_topics,
            }

        # After all combinations for this model are done:
        metrics_vs_combination[name] = metrics_results_model

        # Save results to a file
        filename = f"results_{name}.pkl"
        full_path = os.path.join(save_path, filename)
        with open(full_path, 'wb') as f:
            pickle.dump(metrics_results_model, f)

Note: you may need to restart the kernel to use updated packages.

Usage:
  c:\Users\p70092940\OneDrive - Maastricht University\Desktop\Projects\MyIBDcoach-NLP\mijnidbcoachnlp\.venv\Scripts\python.exe -m pip install [options] <requirement specifier> [package-index-options] ...
  c:\Users\p70092940\OneDrive - Maastricht University\Desktop\Projects\MyIBDcoach-NLP\mijnidbcoachnlp\.venv\Scripts\python.exe -m pip install [options] -r <requirements file> [package-index-options] ...
  c:\Users\p70092940\OneDrive - Maastricht University\Desktop\Projects\MyIBDcoach-NLP\mijnidbcoachnlp\.venv\Scripts\python.exe -m pip install [options] [-e] <vcs project url> ...
  c:\Users\p70092940\OneDrive - Maastricht University\Desktop\Projects\MyIBDcoach-NLP\mijnidbcoachnlp\.venv\Scripts\python.exe -m pip install [options] [-e] <local project path> ...
  c:\Users\p70092940\OneDrive - Maastricht University\Desktop\Projects\MyIBDcoach-NLP\mijnidbcoachnlp\.venv\Scripts\python.exe -m pip install [options] <archive url/path> ...

no such option: -u

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: bertopic in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (0.17.3)
Requirement already satisfied: hdbscan>=0.8.29 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from bertopic) (0.8.40)
Requirement already satisfied: umap-learn>=0.5.0 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from bertopic) (0.5.9.post2)
Requirement already satisfied: numpy>=1.20.0 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from bertopic) (1.26.4)
Requirement already satisfied: pandas>=1.1.5 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from bertopic) (2.3.1)
Requirement already satisfied: plotly>=4.7.0 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from bertopic) (6.2.0)
Requirement already satisfied: scikit-learn>=1.0 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from bertopic) (1.7.1)
Requirement already satisfied: sentence-transformers>=0.4.1 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from bertopic) (5.0.0)
Requirement already satisfied: tqdm>=4.41.1 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from bertopic) (4.67.1)
Requirement already satisfied: llvmlite>0.36.0 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from bertopic) (0.44.0)
Requirement already satisfied: scipy>=1.0 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from hdbscan>=0.8.29->bertopic) (1.13.1)
Requirement already satisfied: joblib>=1.0 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from hdbscan>=0.8.29->bertopic) (1.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from pandas>=1.1.5->bertopic) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from pandas>=1.1.5->bertopic) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from pandas>=1.1.5->bertopic) (2025.2)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from plotly>=4.7.0->bertopic) (1.48.0)
Requirement already satisfied: packaging in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from plotly>=4.7.0->bertopic) (25.0)
Requirement already satisfied: six>=1.5 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.1.5->bertopic) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from scikit-learn>=1.0->bertopic) (3.6.0)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from sentence-transformers>=0.4.1->bertopic) (4.53.3)
Requirement already satisfied: torch>=1.11.0 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from sentence-transformers>=0.4.1->bertopic) (2.7.1)
Requirement already satisfied: huggingface-hub>=0.20.0 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from sentence-transformers>=0.4.1->bertopic) (0.33.4)
Requirement already satisfied: Pillow in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from sentence-transformers>=0.4.1->bertopic) (11.3.0)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from sentence-transformers>=0.4.1->bertopic) (4.14.1)
Requirement already satisfied: filelock in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (3.18.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (2024.11.6)
Requirement already satisfied: requests in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (2.32.4)
Requirement already satisfied: tokenizers<0.22,>=0.21 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.21.2)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.5.3)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2025.7.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.14.0)
Requirement already satisfied: networkx in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.3.0)
Requirement already satisfied: colorama in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from tqdm>=4.41.1->bertopic) (0.4.6)
Requirement already satisfied: numba>=0.51.2 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from umap-learn>=0.5.0->bertopic) (0.61.2)
Requirement already satisfied: pynndescent>=0.5 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from umap-learn>=0.5.0->bertopic) (0.5.13)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.0.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\p70092940\onedrive - maastricht university\desktop\projects\myibdcoach-nlp\mijnidbcoachnlp\.venv\lib\site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (2025.7.14)
Note: you may need to restart the kernel to use updated packages.

c:\Users\p70092940\OneDrive - Maastricht University\Desktop\Projects\MyIBDcoach-NLP\mijnidbcoachnlp\.venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [21]:
# coarse grid search with entire data
save_path = "/workspace/persistent/mijnidbcoachnlp/new_analysis/results/results_per_model"
coarse_metrics_results = coarse_grid_search(
    docs=sentences,
    models_and_embeddings=models_and_embeddings[-1:],
    param_combinations=all_param_combinations,
    tokenized_texts=tokenized_texts,
    dictionary=dictionary,
    save_path=save_path
)

Tuning model: qwen3 at param combination: min_cluster_size = 10, n_components = 5, n_neighbors = 10
Document: 0.6434495002310368
Number of topics: 603
Diversity score: 0.5414593698175788
C_V coherence: 0.34476518477423457
Average embedding cosine similarity weighted: 0.6253377141084465, unweighted: 0.6713576912879944

Tuning model: qwen3 at param combination: min_cluster_size = 10, n_components = 5, n_neighbors = 20
Document: 0.6104963642111919
Number of topics: 494
Diversity score: 0.5580971659919028
C_V coherence: 0.3464373703329996
Average embedding cosine similarity weighted: 0.6261847136692902, unweighted: 0.6726987957954407

Tuning model: qwen3 at param combination: min_cluster_size = 10, n_components = 5, n_neighbors = 30
Document: 0.5734088864028795
Number of topics: 437
Diversity score: 0.576887871853547
C_V coherence: 0.35189604456981116
Average embedding cosine similarity weighted: 0.6283814481198308, unweighted: 0.6710568070411682

Tuning model: qwen3 at param combination: min_cluster_size = 10, n_components = 5, n_neighbors = 40
Document: 0.5656509156351078
Number of topics: 412
Diversity score: 0.5762135922330097
C_V coherence: 0.3538434147891336
Average embedding cosine similarity weighted: 0.6282261914025323, unweighted: 0.6740185618400574

Tuning model: qwen3 at param combination: min_cluster_size = 10, n_components = 7, n_neighbors = 10
Document: 0.6527152897687201
Number of topics: 575
Diversity score: 0.5365217391304348
C_V coherence: 0.34414695155972663
Average embedding cosine similarity weighted: 0.6204739901522391, unweighted: 0.6721464991569519

Tuning model: qwen3 at param combination: min_cluster_size = 10, n_components = 7, n_neighbors = 20
Document: 0.6073834480410516
Number of topics: 479
Diversity score: 0.5582463465553236
C_V coherence: 0.3476197641729684
Average embedding cosine similarity weighted: 0.623863372634481, unweighted: 0.6750558614730835

Tuning model: qwen3 at param combination: min_cluster_size = 10, n_components = 7, n_neighbors = 30
Document: 0.5803399888129576
Number of topics: 441
Diversity score: 0.5648526077097505
C_V coherence: 0.3617337568557383
Average embedding cosine similarity weighted: 0.6285435808317882, unweighted: 0.6767789721488953

Tuning model: qwen3 at param combination: min_cluster_size = 10, n_components = 7, n_neighbors = 40
Document: 0.5638269413166662
Number of topics: 408
Diversity score: 0.5901960784313726
C_V coherence: 0.3572513084757036
Average embedding cosine similarity weighted: 0.6290079606343459, unweighted: 0.6716883182525635

Tuning model: qwen3 at param combination: min_cluster_size = 10, n_components = 10, n_neighbors = 10
Document: 0.6281524356137066
Number of topics: 594
Diversity score: 0.5474747474747474
C_V coherence: 0.3431731876972129
Average embedding cosine similarity weighted: 0.6267143966308976, unweighted: 0.6706234216690063

Tuning model: qwen3 at param combination: min_cluster_size = 10, n_components = 10, n_neighbors = 20
Document: 0.5965855200758773
Number of topics: 477
Diversity score: 0.5712788259958071
C_V coherence: 0.345738731672901
Average embedding cosine similarity weighted: 0.628330129496035, unweighted: 0.6689290404319763

Tuning model: qwen3 at param combination: min_cluster_size = 10, n_components = 10, n_neighbors = 30
Document: 0.5796103990855809
Number of topics: 436
Diversity score: 0.5644495412844037
C_V coherence: 0.3575362828076003
Average embedding cosine similarity weighted: 0.6279261143337198, unweighted: 0.6764779686927795

Tuning model: qwen3 at param combination: min_cluster_size = 10, n_components = 10, n_neighbors = 40
Document: 0.5758408521608016
Number of topics: 409
Diversity score: 0.5792176039119804
C_V coherence: 0.3601422770333204
Average embedding cosine similarity weighted: 0.625339670791317, unweighted: 0.6740104556083679

Tuning model: qwen3 at param combination: min_cluster_size = 10, n_components = 15, n_neighbors = 10
Document: 0.6230453075220701
Number of topics: 596
Diversity score: 0.5432885906040269
C_V coherence: 0.34581857505908414
Average embedding cosine similarity weighted: 0.629207776124567, unweighted: 0.6713039875030518

Tuning model: qwen3 at param combination: min_cluster_size = 10, n_components = 15, n_neighbors = 20
Document: 0.6034923028283762
Number of topics: 469
Diversity score: 0.5590618336886993
C_V coherence: 0.34574216959844356
Average embedding cosine similarity weighted: 0.6232878057593519, unweighted: 0.6725832223892212

Tuning model: qwen3 at param combination: min_cluster_size = 10, n_components = 15, n_neighbors = 30
Document: 0.594688586784698
Number of topics: 422
Diversity score: 0.5680094786729858
C_V coherence: 0.35715385871275773
Average embedding cosine similarity weighted: 0.6215119997935759, unweighted: 0.6782110929489136

Tuning model: qwen3 at param combination: min_cluster_size = 10, n_components = 15, n_neighbors = 40
Document: 0.5799265546341108
Number of topics: 408
Diversity score: 0.5772058823529411
C_V coherence: 0.36138114963365564
Average embedding cosine similarity weighted: 0.6254565360651494, unweighted: 0.6756718754768372

Tuning model: qwen3 at param combination: min_cluster_size = 15, n_components = 5, n_neighbors = 10
Document: 0.630389844110995
Number of topics: 392
Diversity score: 0.5923469387755103
C_V coherence: 0.35148526035961464
Average embedding cosine similarity weighted: 0.6102712908730611, unweighted: 0.6529462933540344

Tuning model: qwen3 at param combination: min_cluster_size = 15, n_components = 5, n_neighbors = 20
Document: 0.5947129064422773
Number of topics: 342
Diversity score: 0.606140350877193
C_V coherence: 0.3526817732277502
Average embedding cosine similarity weighted: 0.6174287958937595, unweighted: 0.655977189540863

Tuning model: qwen3 at param combination: min_cluster_size = 15, n_components = 5, n_neighbors = 30
Document: 0.5937401201391085
Number of topics: 316
Diversity score: 0.6132911392405064
C_V coherence: 0.36300460727448874
Average embedding cosine similarity weighted: 0.6135622800395053, unweighted: 0.6586406826972961

Tuning model: qwen3 at param combination: min_cluster_size = 15, n_components = 5, n_neighbors = 40
Document: 0.5610788200102143
Number of topics: 302
Diversity score: 0.6052980132450331
C_V coherence: 0.35646928588819876
Average embedding cosine similarity weighted: 0.6179955961797675, unweighted: 0.6606029272079468

Tuning model: qwen3 at param combination: min_cluster_size = 15, n_components = 7, n_neighbors = 10
Document: 0.6361536029572704
Number of topics: 388
Diversity score: 0.5930412371134021
C_V coherence: 0.35286355941135683
Average embedding cosine similarity weighted: 0.6080076280824361, unweighted: 0.6534759402275085

Tuning model: qwen3 at param combination: min_cluster_size = 15, n_components = 7, n_neighbors = 20
Document: 0.5861523869743914
Number of topics: 340
Diversity score: 0.6061764705882353
C_V coherence: 0.3519056074800312
Average embedding cosine similarity weighted: 0.6175725961753357, unweighted: 0.6590694785118103

Tuning model: qwen3 at param combination: min_cluster_size = 15, n_components = 7, n_neighbors = 30
Document: 0.5830881101194095
Number of topics: 325
Diversity score: 0.6166153846153846
C_V coherence: 0.35831381989380534
Average embedding cosine similarity weighted: 0.6152265505964035, unweighted: 0.6594802737236023

Tuning model: qwen3 at param combination: min_cluster_size = 15, n_components = 7, n_neighbors = 40
Document: 0.5743816727060483
Number of topics: 293
Diversity score: 0.6109215017064846
C_V coherence: 0.3531011817688194
Average embedding cosine similarity weighted: 0.6143669908222271, unweighted: 0.6573757529258728

Tuning model: qwen3 at param combination: min_cluster_size = 15, n_components = 10, n_neighbors = 10
Document: 0.6340377927478781
Number of topics: 387
Diversity score: 0.5979328165374677
C_V coherence: 0.3488042787679972
Average embedding cosine similarity weighted: 0.6092525644864509, unweighted: 0.651339590549469

Tuning model: qwen3 at param combination: min_cluster_size = 15, n_components = 10, n_neighbors = 20
Document: 0.5928646124662564
Number of topics: 342
Diversity score: 0.6011695906432749
C_V coherence: 0.3529708134173637
Average embedding cosine similarity weighted: 0.6139572328412706, unweighted: 0.6583749651908875

Tuning model: qwen3 at param combination: min_cluster_size = 15, n_components = 10, n_neighbors = 30
Document: 0.5873926895109317
Number of topics: 311
Diversity score: 0.6035369774919614
C_V coherence: 0.35743107177952377
Average embedding cosine similarity weighted: 0.6122423641919468, unweighted: 0.6623678207397461

Tuning model: qwen3 at param combination: min_cluster_size = 15, n_components = 10, n_neighbors = 40
Document: 0.5732872881149833
Number of topics: 291
Diversity score: 0.6120274914089348
C_V coherence: 0.35808152282366995
Average embedding cosine similarity weighted: 0.6116591577467099, unweighted: 0.6622089743614197

Tuning model: qwen3 at param combination: min_cluster_size = 15, n_components = 15, n_neighbors = 10
Document: 0.6225832340280649
Number of topics: 401
Diversity score: 0.5835411471321695
C_V coherence: 0.35072833989169455
Average embedding cosine similarity weighted: 0.6117811566137243, unweighted: 0.6574013829231262

Tuning model: qwen3 at param combination: min_cluster_size = 15, n_components = 15, n_neighbors = 20
Document: 0.6037354994041684
Number of topics: 339
Diversity score: 0.6032448377581121
C_V coherence: 0.3558385876644406
Average embedding cosine similarity weighted: 0.6113592354144455, unweighted: 0.6598451137542725

Tuning model: qwen3 at param combination: min_cluster_size = 15, n_components = 15, n_neighbors = 30
Document: 0.5921350227388799
Number of topics: 308
Diversity score: 0.6081168831168832
C_V coherence: 0.35733078583820926
Average embedding cosine similarity weighted: 0.6116182550430513, unweighted: 0.664186418056488

Tuning model: qwen3 at param combination: min_cluster_size = 15, n_components = 15, n_neighbors = 40
Document: 0.5652374814562611
Number of topics: 300
Diversity score: 0.6073333333333333
C_V coherence: 0.357703734034698
Average embedding cosine similarity weighted: 0.6163293805292968, unweighted: 0.6609934568405151

Tuning model: qwen3 at param combination: min_cluster_size = 20, n_components = 5, n_neighbors = 10
Document: 0.6271066903378001
Number of topics: 302
Diversity score: 0.6182119205298013
C_V coherence: 0.3600614513620887
Average embedding cosine similarity weighted: 0.6021830314040915, unweighted: 0.6358529925346375

Tuning model: qwen3 at param combination: min_cluster_size = 20, n_components = 5, n_neighbors = 20
Document: 0.5983122157640021
Number of topics: 269
Diversity score: 0.6159851301115241
C_V coherence: 0.3620661743372397
Average embedding cosine similarity weighted: 0.607809041967073, unweighted: 0.6453716158866882

Tuning model: qwen3 at param combination: min_cluster_size = 20, n_components = 5, n_neighbors = 30
Document: 0.5784430555217782
Number of topics: 248
Diversity score: 0.632258064516129
C_V coherence: 0.3634189696832052
Average embedding cosine similarity weighted: 0.6068885689777112, unweighted: 0.6473084092140198

Tuning model: qwen3 at param combination: min_cluster_size = 20, n_components = 5, n_neighbors = 40
Document: 0.5828935528587758
Number of topics: 233
Diversity score: 0.628755364806867
C_V coherence: 0.35992313370731616
Average embedding cosine similarity weighted: 0.6006001309393464, unweighted: 0.6449519991874695

Tuning model: qwen3 at param combination: min_cluster_size = 20, n_components = 7, n_neighbors = 10
Document: 0.6134390427782777
Number of topics: 308
Diversity score: 0.615909090909091
C_V coherence: 0.359434438891259
Average embedding cosine similarity weighted: 0.6049527346041045, unweighted: 0.6365739703178406

Tuning model: qwen3 at param combination: min_cluster_size = 20, n_components = 7, n_neighbors = 20
Document: 0.6118825846932076
Number of topics: 259
Diversity score: 0.6150579150579151
C_V coherence: 0.3601304931656664
Average embedding cosine similarity weighted: 0.5981477006499927, unweighted: 0.6519312262535095

Tuning model: qwen3 at param combination: min_cluster_size = 20, n_components = 7, n_neighbors = 30
Document: 0.5715605924268586
Number of topics: 249
Diversity score: 0.6401606425702812
C_V coherence: 0.3587964698535421
Average embedding cosine similarity weighted: 0.606666136902349, unweighted: 0.646023154258728

Tuning model: qwen3 at param combination: min_cluster_size = 20, n_components = 7, n_neighbors = 40
Document: 0.5843284126559498
Number of topics: 228
Diversity score: 0.6456140350877193
C_V coherence: 0.35987430036414675
Average embedding cosine similarity weighted: 0.5991504994485889, unweighted: 0.643828272819519

Tuning model: qwen3 at param combination: min_cluster_size = 20, n_components = 10, n_neighbors = 10
Document: 0.6300493689048858
Number of topics: 293
Diversity score: 0.6109215017064846
C_V coherence: 0.35883821391707343
Average embedding cosine similarity weighted: 0.5977387094081711, unweighted: 0.6377280950546265

Tuning model: qwen3 at param combination: min_cluster_size = 20, n_components = 10, n_neighbors = 20
Document: 0.5921836620540383
Number of topics: 276
Diversity score: 0.618840579710145
C_V coherence: 0.3542278627513224
Average embedding cosine similarity weighted: 0.6074969563738766, unweighted: 0.6497736573219299

Tuning model: qwen3 at param combination: min_cluster_size = 20, n_components = 10, n_neighbors = 30
Document: 0.5881709185534668
Number of topics: 242
Diversity score: 0.6392561983471075
C_V coherence: 0.3628356821549961
Average embedding cosine similarity weighted: 0.6047524421378209, unweighted: 0.6470023393630981

Tuning model: qwen3 at param combination: min_cluster_size = 20, n_components = 10, n_neighbors = 40
Document: 0.5753544590092171
Number of topics: 229
Diversity score: 0.637117903930131
C_V coherence: 0.3701916353273471
Average embedding cosine similarity weighted: 0.6023722670582465, unweighted: 0.6461131572723389

Tuning model: qwen3 at param combination: min_cluster_size = 20, n_components = 15, n_neighbors = 10
Document: 0.626668936501374
Number of topics: 300
Diversity score: 0.615
C_V coherence: 0.3599638126228611
Average embedding cosine similarity weighted: 0.6004409855674028, unweighted: 0.6374161243438721

Tuning model: qwen3 at param combination: min_cluster_size = 20, n_components = 15, n_neighbors = 20
Document: 0.5987256499428488
Number of topics: 265
Diversity score: 0.6173584905660378
C_V coherence: 0.3591813718422943
Average embedding cosine similarity weighted: 0.6041958956870682, unweighted: 0.6458768248558044

Tuning model: qwen3 at param combination: min_cluster_size = 20, n_components = 15, n_neighbors = 30
Document: 0.583914978477103
Number of topics: 249
Diversity score: 0.6321285140562249
C_V coherence: 0.35928625051845686
Average embedding cosine similarity weighted: 0.6058020177296131, unweighted: 0.6488788723945618

Tuning model: qwen3 at param combination: min_cluster_size = 20, n_components = 15, n_neighbors = 40
Document: 0.5656509156351078
Number of topics: 236
Diversity score: 0.6377118644067796
C_V coherence: 0.3652176048025502
Average embedding cosine similarity weighted: 0.606383911765264, unweighted: 0.6487541198730469

Tuning model: qwen3 at param combination: min_cluster_size = 25, n_components = 5, n_neighbors = 10
Document: 0.6232155451251247
Number of topics: 251
Diversity score: 0.6330677290836654
C_V coherence: 0.36841214058773386
Average embedding cosine similarity weighted: 0.5945473223480382, unweighted: 0.621127188205719

Tuning model: qwen3 at param combination: min_cluster_size = 25, n_components = 5, n_neighbors = 20
Document: 0.5998686738490722
Number of topics: 226
Diversity score: 0.6389380530973451
C_V coherence: 0.3675947841260931
Average embedding cosine similarity weighted: 0.5972101126640351, unweighted: 0.6317301988601685

Tuning model: qwen3 at param combination: min_cluster_size = 25, n_components = 5, n_neighbors = 30
Document: 0.5898246552688539
Number of topics: 202
Diversity score: 0.6599009900990099
C_V coherence: 0.3745087947863423
Average embedding cosine similarity weighted: 0.5971446830710347, unweighted: 0.6307942867279053

Tuning model: qwen3 at param combination: min_cluster_size = 25, n_components = 5, n_neighbors = 40
Document: 0.5867360587562928
Number of topics: 188
Diversity score: 0.673936170212766
C_V coherence: 0.3766741632507456
Average embedding cosine similarity weighted: 0.5949600751839951, unweighted: 0.6310645341873169

Tuning model: qwen3 at param combination: min_cluster_size = 25, n_components = 7, n_neighbors = 10
Document: 0.6084048736593789
Number of topics: 257
Diversity score: 0.6392996108949416
C_V coherence: 0.3635183899772607
Average embedding cosine similarity weighted: 0.5977046184068142, unweighted: 0.62140953540802

Tuning model: qwen3 at param combination: min_cluster_size = 25, n_components = 7, n_neighbors = 20
Document: 0.610399085580875
Number of topics: 216
Diversity score: 0.6518518518518519
C_V coherence: 0.3711999241740828
Average embedding cosine similarity weighted: 0.5936697493917871, unweighted: 0.6298400163650513

Tuning model: qwen3 at param combination: min_cluster_size = 25, n_components = 7, n_neighbors = 30
Document: 0.5665750626231183
Number of topics: 209
Diversity score: 0.6636363636363637
C_V coherence: 0.36746328595805744
Average embedding cosine similarity weighted: 0.6015793854135574, unweighted: 0.6317923665046692

Tuning model: qwen3 at param combination: min_cluster_size = 25, n_components = 7, n_neighbors = 40
Document: 0.5945426688392228
Number of topics: 193
Diversity score: 0.6637305699481866
C_V coherence: 0.3746853891274665
Average embedding cosine similarity weighted: 0.5910380870955958, unweighted: 0.6361923217773438

Tuning model: qwen3 at param combination: min_cluster_size = 25, n_components = 10, n_neighbors = 10
Document: 0.6240424134828182
Number of topics: 240
Diversity score: 0.64125
C_V coherence: 0.36750067477393744
Average embedding cosine similarity weighted: 0.5923765006457004, unweighted: 0.6195141077041626

Tuning model: qwen3 at param combination: min_cluster_size = 25, n_components = 10, n_neighbors = 20
Document: 0.5830637904618303
Number of topics: 223
Diversity score: 0.6443946188340807
C_V coherence: 0.3635774894417983
Average embedding cosine similarity weighted: 0.6009931528493684, unweighted: 0.6327455639839172

Tuning model: qwen3 at param combination: min_cluster_size = 25, n_components = 10, n_neighbors = 30
Document: 0.6044407694739659
Number of topics: 199
Diversity score: 0.6542713567839196
C_V coherence: 0.37390540649964266
Average embedding cosine similarity weighted: 0.5934578291133527, unweighted: 0.633574366569519

Tuning model: qwen3 at param combination: min_cluster_size = 25, n_components = 10, n_neighbors = 40
Document: 0.5773486709307133
Number of topics: 192
Diversity score: 0.678125
C_V coherence: 0.375269416634432
Average embedding cosine similarity weighted: 0.5977175751690013, unweighted: 0.6297960877418518

Tuning model: qwen3 at param combination: min_cluster_size = 25, n_components = 15, n_neighbors = 10
Document: 0.619859432379192
Number of topics: 249
Diversity score: 0.6365461847389559
C_V coherence: 0.3651300025025739
Average embedding cosine similarity weighted: 0.5928913546516809, unweighted: 0.6216123700141907

Tuning model: qwen3 at param combination: min_cluster_size = 25, n_components = 15, n_neighbors = 20
Document: 0.5997470755611761
Number of topics: 220
Diversity score: 0.6372727272727273
C_V coherence: 0.36590478726762127
Average embedding cosine similarity weighted: 0.5959885371586474, unweighted: 0.63588547706604

Tuning model: qwen3 at param combination: min_cluster_size = 25, n_components = 15, n_neighbors = 30
Document: 0.5816289306646563
Number of topics: 201
Diversity score: 0.6502487562189054
C_V coherence: 0.3740847417041596

In [1]:
topic_model.get_topic_info()

NameError: name 'topic_model' is not defined

In [23]:
# coarse grid search with entire data
save_path = "/workspace/persistent/mijnidbcoachnlp/new_analysis/results/results_per_model/additional_results"
add_metrics_results = coarse_grid_search(
    docs=sentences,
    models_and_embeddings=models_and_embeddings[3:4],
    param_combinations=untried_param_combos,
    tokenized_texts=tokenized_texts,
    dictionary=dictionary,
    save_path=save_path
)

Tuning model: mpnet at param combination: min_cluster_size = 10, n_components = 7, n_neighbors = 10
Document: 0.6511345120260706
Number of topics: 590
Diversity score: 0.5444067796610169
C_V coherence: 0.35583539591674396
Average embedding cosine similarity weighted: 0.6747417808360442, unweighted: 0.7301112413406372

Tuning model: mpnet at param combination: min_cluster_size = 10, n_components = 7, n_neighbors = 20
Document: 0.6211726938884701
Number of topics: 477
Diversity score: 0.5735849056603773
C_V coherence: 0.3578061751047927
Average embedding cosine similarity weighted: 0.6676825769691924, unweighted: 0.7282949686050415

Tuning model: mpnet at param combination: min_cluster_size = 10, n_components = 7, n_neighbors = 30
Document: 0.5812641358009679
Number of topics: 440
Diversity score: 0.5770454545454545
C_V coherence: 0.35877705597309945
Average embedding cosine similarity weighted: 0.6769837276999718, unweighted: 0.7335137128829956

Tuning model: mpnet at param combination: min_cluster_size = 10, n_components = 7, n_neighbors = 40
Document: 0.5865901408108174
Number of topics: 399
Diversity score: 0.5799498746867168
C_V coherence: 0.3556163757274423
Average embedding cosine similarity weighted: 0.6725370360275802, unweighted: 0.7359248995780945

Tuning model: mpnet at param combination: min_cluster_size = 15, n_components = 5, n_neighbors = 10
Document: 0.6823366327002116
Number of topics: 372
Diversity score: 0.6029569892473118
C_V coherence: 0.36070761918541383
Average embedding cosine similarity weighted: 0.6396443979676495, unweighted: 0.7051109671592712

Tuning model: mpnet at param combination: min_cluster_size = 15, n_components = 5, n_neighbors = 20
Document: 0.5835988229285731
Number of topics: 358
Diversity score: 0.6033519553072626
C_V coherence: 0.35746462366989606
Average embedding cosine similarity weighted: 0.6679520776653138, unweighted: 0.720180332660675

Tuning model: mpnet at param combination: min_cluster_size = 15, n_components = 5, n_neighbors = 30
Document: 0.5766434008609159
Number of topics: 320
Diversity score: 0.5984375
C_V coherence: 0.35902905467687773
Average embedding cosine similarity weighted: 0.6657496981822697, unweighted: 0.7230147123336792

Tuning model: mpnet at param combination: min_cluster_size = 15, n_components = 5, n_neighbors = 40
Document: 0.5956370534302877
Number of topics: 291
Diversity score: 0.6030927835051546
C_V coherence: 0.3574609999487971
Average embedding cosine similarity weighted: 0.6540638132873516, unweighted: 0.7261260747909546

Tuning model: mpnet at param combination: min_cluster_size = 15, n_components = 7, n_neighbors = 10
Document: 0.6997738271845132
Number of topics: 368
Diversity score: 0.6016304347826087
C_V coherence: 0.35906070182582994
Average embedding cosine similarity weighted: 0.6334795464342146, unweighted: 0.7124332189559937

Tuning model: mpnet at param combination: min_cluster_size = 15, n_components = 7, n_neighbors = 20
Document: 0.5957829713757631
Number of topics: 351
Diversity score: 0.6005698005698006
C_V coherence: 0.3584534770188376
Average embedding cosine similarity weighted: 0.6638319546353604, unweighted: 0.7211830019950867

Tuning model: mpnet at param combination: min_cluster_size = 15, n_components = 7, n_neighbors = 30
Document: 0.627982198010652
Number of topics: 305
Diversity score: 0.6068852459016394
C_V coherence: 0.3530735015311639
Average embedding cosine similarity weighted: 0.6510502025744721, unweighted: 0.7181630730628967

Tuning model: mpnet at param combination: min_cluster_size = 15, n_components = 7, n_neighbors = 40
Document: 0.6145820666845011
Number of topics: 284
Diversity score: 0.604225352112676
C_V coherence: 0.35293684028905986
Average embedding cosine similarity weighted: 0.6494482907025344, unweighted: 0.7258908748626709

Tuning model: mpnet at param combination: min_cluster_size = 15, n_components = 10, n_neighbors = 10
Document: 0.6938398307351833
Number of topics: 366
Diversity score: 0.6030054644808743
C_V coherence: 0.35564696158921955
Average embedding cosine similarity weighted: 0.6343135135239816, unweighted: 0.7109162211418152

Tuning model: mpnet at param combination: min_cluster_size = 15, n_components = 10, n_neighbors = 20
Document: 0.6131958462024855
Number of topics: 336
Diversity score: 0.6005952380952381
C_V coherence: 0.36017069604060853
Average embedding cosine similarity weighted: 0.6606002483344658, unweighted: 0.7184252738952637

Tuning model: mpnet at param combination: min_cluster_size = 15, n_components = 10, n_neighbors = 30
Document: 0.5759867701062769
Number of topics: 326
Diversity score: 0.600920245398773
C_V coherence: 0.3559438068199807
Average embedding cosine similarity weighted: 0.6664719179277685, unweighted: 0.7221173048019409

Tuning model: mpnet at param combination: min_cluster_size = 15, n_components = 10, n_neighbors = 40
Document: 0.6074807266713684
Number of topics: 285
Diversity score: 0.6056140350877193
C_V coherence: 0.3552522415286519
Average embedding cosine similarity weighted: 0.65082821386094, unweighted: 0.7280227541923523

Tuning model: mpnet at param combination: min_cluster_size = 15, n_components = 15, n_neighbors = 10
Document: 0.6612028502638683
Number of topics: 376
Diversity score: 0.597872340425532
C_V coherence: 0.3574812941235149
Average embedding cosine similarity weighted: 0.645762216304705, unweighted: 0.7096760272979736

Tuning model: mpnet at param combination: min_cluster_size = 15, n_components = 15, n_neighbors = 20
Document: 0.5832826673800433
Number of topics: 352
Diversity score: 0.5988636363636364
C_V coherence: 0.361133442574134
Average embedding cosine similarity weighted: 0.6673786480307797, unweighted: 0.7215836644172668

Tuning model: mpnet at param combination: min_cluster_size = 15, n_components = 15, n_neighbors = 30
Document: 0.5669155378292273
Number of topics: 332
Diversity score: 0.5930722891566265
C_V coherence: 0.355894462688987
Average embedding cosine similarity weighted: 0.6703274198290996, unweighted: 0.7244006991386414

Tuning model: mpnet at param combination: min_cluster_size = 15, n_components = 15, n_neighbors = 40
Document: 0.5926214158904642
Number of topics: 290
Diversity score: 0.6096551724137931
C_V coherence: 0.3568368111282077
Average embedding cosine similarity weighted: 0.6513881095264961, unweighted: 0.7295039892196655

Tuning model: mpnet at param combination: min_cluster_size = 20, n_components = 7, n_neighbors = 10
Document: 0.6881003915464871
Number of topics: 280
Diversity score: 0.6375
C_V coherence: 0.357449958000676
Average embedding cosine similarity weighted: 0.6252353774993135, unweighted: 0.6919854283332825

Tuning model: mpnet at param combination: min_cluster_size = 20, n_components = 7, n_neighbors = 20
Document: 0.6359590456966366
Number of topics: 264
Diversity score: 0.6223484848484848
C_V coherence: 0.35826057682892676
Average embedding cosine similarity weighted: 0.6404164349930236, unweighted: 0.7055754661560059

Tuning model: mpnet at param combination: min_cluster_size = 20, n_components = 7, n_neighbors = 30
Document: 0.6337945961720859
Number of topics: 241
Diversity score: 0.6360995850622406
C_V coherence: 0.35658130426434215
Average embedding cosine similarity weighted: 0.6410984761238483, unweighted: 0.7037417888641357

Tuning model: mpnet at param combination: min_cluster_size = 20, n_components = 7, n_neighbors = 40
Document: 0.6023492789221527
Number of topics: 234
Diversity score: 0.6299145299145299
C_V coherence: 0.3549435576157871
Average embedding cosine similarity weighted: 0.6448629015517596, unweighted: 0.710679292678833

Tuning model: mpnet at param combination: min_cluster_size = 25, n_components = 5, n_neighbors = 10
Document: 0.6845497215399207
Number of topics: 229
Diversity score: 0.6602620087336245
C_V coherence: 0.35307688802852194
Average embedding cosine similarity weighted: 0.6197298500002387, unweighted: 0.6675653457641602

Tuning model: mpnet at param combination: min_cluster_size = 25, n_components = 5, n_neighbors = 20
Document: 0.620613341764148
Number of topics: 209
Diversity score: 0.6665071770334928
C_V coherence: 0.3571444452560793
Average embedding cosine similarity weighted: 0.6341656910583205, unweighted: 0.6865220665931702

Tuning model: mpnet at param combination: min_cluster_size = 25, n_components = 5, n_neighbors = 30
Document: 0.605121719886184
Number of topics: 196
Diversity score: 0.6571428571428571
C_V coherence: 0.36870579241601925
Average embedding cosine similarity weighted: 0.635894009951715, unweighted: 0.6892281174659729

Tuning model: mpnet at param combination: min_cluster_size = 25, n_components = 5, n_neighbors = 40
Document: 0.5918188671903499
Number of topics: 186
Diversity score: 0.6602150537634408
C_V coherence: 0.36144052732737775
Average embedding cosine similarity weighted: 0.6363464236332941, unweighted: 0.6918483972549438

Tuning model: mpnet at param combination: min_cluster_size = 25, n_components = 7, n_neighbors = 10
Document: 0.6760378413871933
Number of topics: 230
Diversity score: 0.6656521739130434
C_V coherence: 0.3610898248844007
Average embedding cosine similarity weighted: 0.6250691030195131, unweighted: 0.6714723110198975

Tuning model: mpnet at param combination: min_cluster_size = 25, n_components = 7, n_neighbors = 20
Document: 0.6325299739779664
Number of topics: 212
Diversity score: 0.6650943396226415
C_V coherence: 0.3618767667129603
Average embedding cosine similarity weighted: 0.6321062719578093, unweighted: 0.6861186623573303

Tuning model: mpnet at param combination: min_cluster_size = 25, n_components = 7, n_neighbors = 30
Document: 0.6038327780344853
Number of topics: 195
Diversity score: 0.6553846153846153
C_V coherence: 0.3622154970587009
Average embedding cosine similarity weighted: 0.6378785355324241, unweighted: 0.6874477863311768

Tuning model: mpnet at param combination: min_cluster_size = 25, n_components = 7, n_neighbors = 40
Document: 0.5951020209635448
Number of topics: 179
Diversity score: 0.676536312849162
C_V coherence: 0.3610608049872856
Average embedding cosine similarity weighted: 0.6354319983299381, unweighted: 0.6854181289672852

Tuning model: mpnet at param combination: min_cluster_size = 25, n_components = 10, n_neighbors = 10
Document: 0.6450789172888446
Number of topics: 233
Diversity score: 0.6553648068669528
C_V coherence: 0.35724408362760873
Average embedding cosine similarity weighted: 0.6320438479849126, unweighted: 0.6736190915107727

Tuning model: mpnet at param combination: min_cluster_size = 25, n_components = 10, n_neighbors = 20
Document: 0.6232398647827039
Number of topics: 204
Diversity score: 0.6583333333333333
C_V coherence: 0.3672557243066081
Average embedding cosine similarity weighted: 0.6331369946276667, unweighted: 0.6851739287376404

Tuning model: mpnet at param combination: min_cluster_size = 25, n_components = 10, n_neighbors = 30
Document: 0.6096694958534984
Number of topics: 193
Diversity score: 0.6549222797927461
C_V coherence: 0.3647359586813476
Average embedding cosine similarity weighted: 0.6347089392269436, unweighted: 0.6885769963264465

Tuning model: mpnet at param combination: min_cluster_size = 25, n_components = 10, n_neighbors = 40
Document: 0.5852525596439602
Number of topics: 191
Diversity score: 0.6581151832460733
C_V coherence: 0.3657160095789297
Average embedding cosine similarity weighted: 0.6384232670582681, unweighted: 0.6929032206535339

Tuning model: mpnet at param combination: min_cluster_size = 25, n_components = 15, n_neighbors = 10
Document: 0.6645346433522216
Number of topics: 219
Diversity score: 0.6547945205479452
C_V coherence: 0.362546727821746
Average embedding cosine similarity weighted: 0.6211320169977605, unweighted: 0.6716559529304504

Tuning model: mpnet at param combination: min_cluster_size = 25, n_components = 15, n_neighbors = 20
Document: 0.6161628444271504
Number of topics: 215
Diversity score: 0.6558139534883721
C_V coherence: 0.3647234740228062
Average embedding cosine similarity weighted: 0.6361571183274664, unweighted: 0.6867369413375854

Tuning model: mpnet at param combination: min_cluster_size = 25, n_components = 15, n_neighbors = 30
Document: 0.6078455215350568
Number of topics: 205
Diversity score: 0.6546341463414634
C_V coherence: 0.36511015329909974
Average embedding cosine similarity weighted: 0.6386182509232132, unweighted: 0.6923745274543762

Tuning model: mpnet at param combination: min_cluster_size = 25, n_components = 15, n_neighbors = 40
Document: 0.5902380894477006
Number of topics: 184
Diversity score: 0.6701086956521739
C_V coherence: 0.36649370763798944
Average embedding cosine similarity weighted: 0.6352775322885046, unweighted: 0.6870205402374268

Tuning model: mpnet at param combination: min_cluster_size = 30, n_components = 7, n_neighbors = 10
Document: 0.6611055716335514
Number of topics: 194
Diversity score: 0.6706185567010309
C_V coherence: 0.3659942028771899
Average embedding cosine similarity weighted: 0.6184797251521401, unweighted: 0.6662518382072449

Tuning model: mpnet at param combination: min_cluster_size = 30, n_components = 7, n_neighbors = 20
Document: 0.6057297113256646
Number of topics: 178
Diversity score: 0.6567415730337078
C_V coherence: 0.37173497940606764
Average embedding cosine similarity weighted: 0.6307179180871346, unweighted: 0.6828876733779907

Tuning model: mpnet at param combination: min_cluster_size = 30, n_components = 7, n_neighbors = 30
Document: 0.5985554123397943
Number of topics: 169
Diversity score: 0.6526627218934912
C_V coherence: 0.37646685495093146
Average embedding cosine similarity weighted: 0.6304832218481567, unweighted: 0.682832658290863

Tuning model: mpnet at param combination: min_cluster_size = 30, n_components = 7, n_neighbors = 40
Document: 0.5944940295240643
Number of topics: 160
Diversity score: 0.6575
C_V coherence: 0.3706409702175804
Average embedding cosine similarity weighted: 0.6282855645611526, unweighted: 0.6838338971138

Tuning model: mpnet at param combination: min_cluster_size = 35, n_components = 5, n_neighbors = 10
Document: 0.6359833653542158
Number of topics: 169
Diversity score: 0.6644970414201183
C_V coherence: 0.36038462788934467
Average embedding cosine similarity weighted: 0.6174651085669431, unweighted: 0.6511601805686951

Tuning model: mpnet at param combination: min_cluster_size = 35, n_components = 5, n_neighbors = 20
Document: 0.5877818040321993
Number of topics: 157
Diversity score: 0.6789808917197452
C_V coherence: 0.3671150422889585
Average embedding cosine similarity weighted: 0.6264076406133303, unweighted: 0.6734192371368408

Tuning model: mpnet at param combination: min_cluster_size = 35, n_components = 5, n_neighbors = 30
Document: 0.6057540309832438
Number of topics: 150
Diversity score: 0.662
C_V coherence: 0.3704554377664653
Average embedding cosine similarity weighted: 0.6227973065223418, unweighted: 0.673346996307373

Tuning model: mpnet at param combination: min_cluster_size = 35, n_components = 5, n_neighbors = 40
Document: 0.5838906588195238
Number of topics: 145
Diversity score: 0.6724137931034483
C_V coherence: 0.373229382442723
Average embedding cosine similarity weighted: 0.6254817867915591, unweighted: 0.6787403225898743

Tuning model: mpnet at param combination: min_cluster_size = 35, n_components = 7, n_neighbors = 10
Document: 0.6139011162722828
Number of topics: 170
Diversity score: 0.6729411764705883
C_V coherence: 0.36514597828975964
Average embedding cosine similarity weighted: 0.6201370115767605, unweighted: 0.658036470413208

Tuning model: mpnet at param combination: min_cluster_size = 35, n_components = 7, n_neighbors = 20
Document: 0.6000389114521267
Number of topics: 152
Diversity score: 0.6796052631578947
C_V coherence: 0.36941324196636705
Average embedding cosine similarity weighted: 0.6260577928757574, unweighted: 0.6694658398628235

Tuning model: mpnet at param combination: min_cluster_size = 35, n_components = 7, n_neighbors = 30
Document: 0.5868576570441888
Number of topics: 155
Diversity score: 0.6612903225806451
C_V coherence: 0.37434817136498977
Average embedding cosine similarity weighted: 0.6284254133827297, unweighted: 0.6802170872688293

Tuning model: mpnet at param combination: min_cluster_size = 35, n_components = 7, n_neighbors = 40
Document: 0.5837447408740485
Number of topics: 143
Diversity score: 0.6734265734265734
C_V coherence: 0.3769297394608597
Average embedding cosine similarity weighted: 0.6237311529806792, unweighted: 0.6767593026161194

Tuning model: mpnet at param combination: min_cluster_size = 35, n_components = 10, n_neighbors = 10
Document: 0.6231912254675455
Number of topics: 160
Diversity score: 0.65875
C_V coherence: 0.3739601234005149
Average embedding cosine similarity weighted: 0.6169104365430227, unweighted: 0.6590763330459595

Tuning model: mpnet at param combination: min_cluster_size = 35, n_components = 10, n_neighbors = 20
Document: 0.6029815900192125
Number of topics: 153
Diversity score: 0.6699346405228758
C_V coherence: 0.37322413802667104
Average embedding cosine similarity weighted: 0.6227102417844702, unweighted: 0.6725916862487793

Tuning model: mpnet at param combination: min_cluster_size = 35, n_components = 10, n_neighbors = 30
Document: 0.5982635764488436
Number of topics: 145
Diversity score: 0.6648275862068965
C_V coherence: 0.3686565151300514
Average embedding cosine similarity weighted: 0.6221510053565347, unweighted: 0.6738308668136597

Tuning model: mpnet at param combination: min_cluster_size = 35, n_components = 10, n_neighbors = 40
Document: 0.5807777426493835
Number of topics: 142
Diversity score: 0.6746478873239437
C_V coherence: 0.37372615174155205
Average embedding cosine similarity weighted: 0.6250937033523732, unweighted: 0.6768290996551514

Tuning model: mpnet at param combination: min_cluster_size = 35, n_components = 15, n_neighbors = 10
Document: 0.6489214231863616
Number of topics: 161
Diversity score: 0.6701863354037267
C_V coherence: 0.3662397739766054
Average embedding cosine similarity weighted: 0.6106969756227301, unweighted: 0.6566876769065857

Tuning model: mpnet at param combination: min_cluster_size = 35, n_components = 15, n_neighbors = 20
Document: 0.6062404241348281
Number of topics: 151
Diversity score: 0.6655629139072847
C_V coherence: 0.37600022088125856
Average embedding cosine similarity weighted: 0.6228143587464584, unweighted: 0.6730990409851074

Tuning model: mpnet at param combination: min_cluster_size = 35, n_components = 15, n_neighbors = 30
Document: 0.6073834480410516
Number of topics: 149
Diversity score: 0.6751677852348993
C_V coherence: 0.3663145166847937
Average embedding cosine similarity weighted: 0.6218658120531936, unweighted: 0.6784847378730774

Tuning model: mpnet at param combination: min_cluster_size = 35, n_components = 15, n_neighbors = 40
Document: 0.5876115664291447
Number of topics: 140
Diversity score: 0.6778571428571428
C_V coherence: 0.37350658672497783
Average embedding cosine similarity weighted: 0.6228749823078357, unweighted: 0.6781086921691895

Tuning model: mpnet at param combination: min_cluster_size = 40, n_components = 7, n_neighbors = 10
Document: 0.6117366667477322
Number of topics: 156
Diversity score: 0.6717948717948717
C_V coherence: 0.36979604566166396
Average embedding cosine similarity weighted: 0.6163776215502631, unweighted: 0.6576708555221558

Tuning model: mpnet at param combination: min_cluster_size = 40, n_components = 7, n_neighbors = 20
Document: 0.6094506189352854
Number of topics: 132
Diversity score: 0.6871212121212121
C_V coherence: 0.37324541626482377
Average embedding cosine similarity weighted: 0.6172366199784534, unweighted: 0.6558424234390259

Tuning model: mpnet at param combination: min_cluster_size = 40, n_components = 7, n_neighbors = 30
Document: 0.6007928208370826
Number of topics: 131
Diversity score: 0.6717557251908397
C_V coherence: 0.3744301861937571

#### Results for GROW Science Day

In [23]:
'''
from bertopic import BERTopic

embedding_model = SentenceTransformer("sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2")
embeddings =  np.load("/workspace/persistent/mijnidbcoachnlp/data/embeddings/embeddings_st_miniL12v2_sentence_placeholder.npy")

topic_model = BERTopic(**bertopic_settings)
topic_model.hdbscan_model = HDBSCAN(min_cluster_size=25, metric='euclidean', cluster_selection_method='eom', prediction_data=False)
topic_model.umap_model = UMAP(n_neighbors=15, n_components=6, min_dist=0.0, metric='cosine', random_state=42)
topics, probs = topic_model.fit_transform(sentences, embeddings)

'''

'\nfrom bertopic import BERTopic\n\nembedding_model = SentenceTransformer("sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2")\nembeddings =  np.load("/workspace/persistent/mijnidbcoachnlp/data/embeddings/embeddings_st_miniL12v2_sentence_placeholder.npy")\n\ntopic_model = BERTopic(**bertopic_settings)\ntopic_model.hdbscan_model = HDBSCAN(min_cluster_size=25, metric=\'euclidean\', cluster_selection_method=\'eom\', prediction_data=False)\ntopic_model.umap_model = UMAP(n_neighbors=15, n_components=6, min_dist=0.0, metric=\'cosine\', random_state=42)\ntopics, probs = topic_model.fit_transform(sentences, embeddings)\n\n'

In [24]:
'''
import matplotlib.pyplot as plt

# Get topic info
topic_info = topic_model.get_topic_info()

# Exclude outlier topic -1 and get top 10 topics
top_10 = topic_info[topic_info.Topic != -1].head(10)

# Prepare labels: "Topic #ID: word1, word2, word3"
labels = [f"{', '.join(row['Representation'][:3])}" for _, row in top_10.iterrows()]
frequencies = top_10["Count"].values

# Plot
plt.figure(figsize=(10, 6))
bars = plt.barh(labels, frequencies, color="skyblue")
plt.xlabel("Number of Documents")
plt.title("Top 10 Topics by Frequency")
plt.gca().invert_yaxis()  # Highest at the top

# Optional: Add counts next to bars
for bar in bars:
    width = bar.get_width()
    plt.text(width + 2, bar.get_y() + bar.get_height()/2,
             f'{int(width)}', va='center')

plt.tight_layout()
plt.show()
'''

'\nimport matplotlib.pyplot as plt\n\n# Get topic info\ntopic_info = topic_model.get_topic_info()\n\n# Exclude outlier topic -1 and get top 10 topics\ntop_10 = topic_info[topic_info.Topic != -1].head(10)\n\n# Prepare labels: "Topic #ID: word1, word2, word3"\nlabels = [f"{\', \'.join(row[\'Representation\'][:3])}" for _, row in top_10.iterrows()]\nfrequencies = top_10["Count"].values\n\n# Plot\nplt.figure(figsize=(10, 6))\nbars = plt.barh(labels, frequencies, color="skyblue")\nplt.xlabel("Number of Documents")\nplt.title("Top 10 Topics by Frequency")\nplt.gca().invert_yaxis()  # Highest at the top\n\n# Optional: Add counts next to bars\nfor bar in bars:\n    width = bar.get_width()\n    plt.text(width + 2, bar.get_y() + bar.get_height()/2,\n             f\'{int(width)}\', va=\'center\')\n\nplt.tight_layout()\nplt.show()\n'

## 5. Fine Grid Search

In [25]:
 # access the three params
test_combo = (40, 10, 10)
name = "e5"
embeddings = models_and_embeddings_dict[name][1]
min_cluster_size, n_components, n_neighbors = test_combo

# initialize a topic model with the basic setting
topic_model = BERTopic(**bertopic_settings)

# update the hdbscan model and umap model with the three parameters
topic_model.hdbscan_model = HDBSCAN(min_cluster_size=min_cluster_size, metric='euclidean', cluster_selection_method='eom', prediction_data=False)
topic_model.umap_model = UMAP(n_neighbors=n_neighbors, n_components=n_components, min_dist=0.0, metric='cosine', random_state=42)
print(f"Tuning model: {name} at param combination: min_cluster_size = {min_cluster_size}, n_components = {n_components}, n_neighbors = {n_neighbors}")

topics, probs = topic_model.fit_transform(sentences, embeddings)

Tuning model: e5 at param combination: min_cluster_size = 40, n_components = 10, n_neighbors = 10

In [26]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,16791,-1_last_pijn_afspraak_ontlasting,"[last, pijn, afspraak, ontlasting, gaat, goed,...","[Ik wil deze afspraak gewoon door laten gaan.,..."
1,0,7522,0_apotheek_recept_humira_medicatie,"[apotheek, recept, humira, medicatie, infuus, ...","[Goedemorgen, Zou het mogelijk zijn om een ni..."
2,1,966,1_afspraak_poli_staan_gepland,"[afspraak, poli, staan, gepland, telefonische,...","[Afspraak 29-6 2015 om 8.45., Ik had maandag [..."
3,2,891,2_mee_hieraan_nakijken_alternatief,"[mee, hieraan, nakijken, alternatief, mogelijk...","[Wat kan ik hier het beste mee doen., Wat kan ..."
4,3,598,3_crohn_ziekte_colitis_ulcerosa,"[crohn, ziekte, colitis, ulcerosa, darmen, col...",[Zou het kunnen dat dit te maken heeft met Cro...
...,...,...,...,...,...
109,108,42,108_keel_koorts_keelpijn_hoofdpijn,"[keel, koorts, keelpijn, hoofdpijn, kortademig...",[Ik heb het gevoel dat er een brok blijft vast...
110,109,41,109_mdl_arts_mdlarts_vervolgen,"[mdl, arts, mdlarts, vervolgen, behandeling, h...",[Waarom niet bij mijn mdl arts waar ik onder b...
111,110,41,110_adres_oude_verhuisd_wonen,"[adres, oude, verhuisd, wonen, postcode, verhu...","[Mijn nieuwe adres is [LOCATIE], [LOCATIE]., I..."
112,111,41,111_darmen_last_darmklachten_darmspoelen,"[darmen, last, darmklachten, darmspoelen, afst...","[Hallo, Sinds 2 weken heb ik meer last van mij..."
113,112,41,112_hoor_graag_bvd_vrgr,"[hoor, graag, bvd, vrgr, mvrgr, julie, hoort, ...","[Graag hoor ik van je., Ik hoor het graag van ..."

In [26]:
coverage = get_coverage(topic_model)
nr_topics = get_nr_topics(topic_model)

print(f"Document: {coverage}")
print(f"Number of topics: {nr_topics}")

Document: 0.5807777426493835
Number of topics: 126