## 1. Read data

### 1.1. The dataset of sentences

In [2]:
import pandas as pd
sentence_df = pd.read_excel("/workspace/mijnidbcoachnlp/data/analysis_datasets/sentence_data.xlsx")

ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.

In [2]:
sentences = sentence_df["Clean_Sentence"].to_list()

### 1.2. Import list of stopwords

In [3]:
### Importing the list of Dutch stopwords (note that there are customized dutch words in there)

with open('/workspace/mijnidbcoachnlp/data/analysis_datasets/stopwords.txt', 'r') as file:
    lines = [line.strip() for line in file.readlines()]

dutch_stopwords = lines

extra_list = [
    'maandag', 'dinsdag', 'woensdag', 'donderdag', 'vrijdag', 'zaterdag', 'zondag',
    'januari', 'februari', 'maart', 'april', 'mei', 'juni', 'juli', 'augustus', 'september', 'oktober', 'november', 'december',
    'jan', 'feb', 'mrt', 'apr', 'mei', 'jun', 'jul', 'aug', 'sep', 'okt', 'nov', 'dec', "jl", "weken", "week", "dagen", "dag", "mg"
]

dutch_stopwords.extend(extra_list)

## 2. Download the embedding model BERTje

### 2.1 Download BERTje

In [4]:
from transformers.pipelines import pipeline
from transformers import AutoTokenizer, AutoModel, TFAutoModel
embedding_model = pipeline("feature-extraction", model="GroNLP/bert-base-dutch-cased")

Some weights of BertModel were not initialized from the model checkpoint at GroNLP/bert-base-dutch-cased and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

### 2.2 Pre-calculate and save sentence embeddings (skip if there are saved embeddings and go to 2.3)

In [ ]:
# pre-calculate the embeddings of the dutch sentences
import numpy as np

embeddings_nl = embedding_model(sentences, truncation=True, padding=True)
sentence_embeddings_nl = np.array([np.mean(embedding, axis=1).flatten() for embedding in embeddings_nl])

In [ ]:
from tqdm import tqdm 
# Initialize an empty list to store embeddings
sentence_embeddings_nl = []

# Use tqdm to track progress
for sentence in tqdm(sentences, desc="Processing Embeddings", unit="sentence"):
    # Compute embedding for the sentence
    embedding = embedding_model(sentence)
    # Average token embeddings to create a sentence-level embedding
    sentence_embedding = np.mean(embedding[0], axis=0)
    # Append to the list
    sentence_embeddings_nl.append(sentence_embedding)

# Convert the list to a NumPy array
sentence_embeddings_nl = np.array(sentence_embeddings_nl)

# Check the shape of the resulting embeddings
print(f"Shape of sentence embeddings: {sentence_embeddings_nl.shape}")

In [ ]:
# save the sentence embeddings
import numpy as np
np.save('/workspace/mijnidbcoachnlp/data/embeddings/sentence_embeddings_bertje_nl_new.npy', sentence_embeddings_nl)

### 2.3 Load saved embeddings

In [30]:
# load the save model
import numpy as np

loaded_embeddings_nl = np.load('/workspace/mijnidbcoachnlp/data/embeddings/sentence_embeddings_bertje_nl_new.npy')

In [31]:
embeddings=loaded_embeddings_nl

## 3. Preparation for Model Evaluation

### 3.1 Import the annotated sample set

In [386]:
annotated_df = pd.read_excel("/workspace/mijnidbcoachnlp/data/analysis_datasets/sample_sentences_for_labeling_100.xlsx", index_col=0)

In [387]:
annotated_df.head()

,Message_ID,Sentence,Clean_Sentence,Sentence_ID,Translated_Sentence,Manual_Label
269,173,"Beste [PERSOON-1], het gaat weer iets beter en ik heb gisteren de test proberen te doen.",het gaat weer iets beter en ik heb gisteren de test proberen te doen.,269,"Dear [PERSOON-1], things are getting better and I tried to do the test yesterday.",A4
270,173,Het liep goed totdat ik probeerde de onderkant van het buisje te breken.,Het liep goed totdat ik probeerde de onderkant van het buisje te breken.,270,It went well until I tried to break the bottom of the tube.,A4
271,173,Ik kreeg het niet voor elkaar en heb toen meer kracht gebruikt.,Ik kreeg het niet voor elkaar en heb toen meer kracht gebruikt.,271,I couldn't do it and then I used more power.,A5
272,173,Hij lijkt me nu op de verkeerde plek gebroken (zie foto).,j lijkt me nu op de verkeerde plek gebroken (zie foto).,272,It looks like it's broken in the wrong place (see picture).,A5
273,173,De test is uiteindelijk mislukt volgens de app.,De test is uiteindelijk mislukt volgens de app.,273,The test ultimately failed according to the app.,A4

### 3.2 Function to build model with different clustering methods

In [16]:
# set the vectorizer model
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.cluster import AgglomerativeClustering
from sklearn.cluster import KMeans
from umap import UMAP
from hdbscan import HDBSCAN
from bertopic.vectorizers import ClassTfidfTransformer
from bertopic.representation import KeyBERTInspired


kmeans_model = KMeans(n_clusters=100)
agglo_model = AgglomerativeClustering(n_clusters=100)
# dimension reduction
ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True)
representation_model = KeyBERTInspired()

In [407]:
# function to build the model with different selection of clustering method
# build the BERTopic model
from bertopic import BERTopic
from umap import UMAP
from bertopic import BERTopic
from sklearn.feature_extraction.text import CountVectorizer

def build_bertopic():
    # Initialize BERTopic with UMAP and HDBSCAN models
    topic_model = BERTopic(
        embedding_model=embedding_model,
        umap_model=UMAP(n_neighbors=10, n_components=2, metric='cosine', random_state=42),
        hdbscan_model=HDBSCAN(min_cluster_size=20, min_samples=10, metric='euclidean', cluster_selection_method='eom', prediction_data=True),
        vectorizer_model=CountVectorizer(stop_words=dutch_stopwords, min_df=2, ngram_range=(1, 2), token_pattern=r'\b[a-zA-Z]{3,}\b'),
        top_n_words=10,
        verbose=True
    )

    # Fit-transform to get document topics and probabilities
    topics, probs = topic_model.fit_transform(sentences, embeddings)
    

    # Return only essential results
    return topic_model

## 4. BERTje-HDBSCAN model

In [408]:
topic_model = build_bertopic()

2024-11-18 22:17:57,711 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-11-18 22:18:48,173 - BERTopic - Dimensionality - Completed ✓
2024-11-18 22:18:48,177 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-11-18 22:18:50,734 - BERTopic - Cluster - Completed ✓
2024-11-18 22:18:50,750 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-11-18 22:18:52,110 - BERTopic - Representation - Completed ✓

In [35]:
# save topic model 
topic_model.save("/workspace/mijnidbcoachnlp/data/result_data/saved_BERTje_model", serialization="pytorch", save_ctfidf=True, save_embedding_model=embedding_model)

In [389]:
loaded_topic_model = BERTopic.load("/workspace/mijnidbcoachnlp/data/result_data/saved_BERTje_model", embedding_model=embedding_model)

In [409]:

topic_model.get_topic_info()[:10]

,Topic,Count,Name,Representation,Representative_Docs
0,-1,19884,-1_afspraak_ontlasting_bloed_goed,"[afspraak, ontlasting, bloed, goed, keer, gaan, gaat, last, vandaag, laatste]","[En moet ik van te voren echt zo’n vies laxeerdrank drinken aangezien ik geen Dikke darm meer heb, de vorige keer toen ik opgenomen was hoefde dat niet., ( ik weet dat bijv een tandartsafspraak niet mag 2 weken voor/ na het infuus.), Ok, dan ga ik deze week nog bloed laten prikken.]"
1,0,474,0_sturen_recept sturen_apotheek sturen_recept apotheek,"[sturen, recept sturen, apotheek sturen, recept apotheek, wilt, vertellen, nakijken, recept, apotheek, doorgeven]","[Zou u voor mij een nieuw recept naar mijn apotheek kunnen sturen?, Kunt u een nieuw recept naar apotheek voor mij sturen?, Zouden jullie een nieuw recept naar mijn apotheek in willen sturen?]"
2,1,471,1_ziekenhuis_apotheek ziekenhuis_ziekenhuis ziekenhuis_ziekenhuis apotheek,"[ziekenhuis, apotheek ziekenhuis, ziekenhuis ziekenhuis, ziekenhuis apotheek, prikken ziekenhuis, apotheek, ziekenhuis recept, zorginstelling, afspraak ziekenhuis, ziekenhuis sturen]","[Gewoon in het [ZIEKENHUIS]., Het was in het [ZIEKENHUIS]., Dit ga ik nu doen in het [ZIEKENHUIS].]"
3,2,406,2_dankjewel_dank_bedankt_alvast,"[dankjewel, dank, bedankt, alvast, fijn dankjewel, fijn dank, dankjewel bedankt, fijn, bedankt dankjewel, dank dank]","[is het nog steeds, dankjewel!, Dankjewel dat zal ik doen ., Dan doe ik dat :) dankjewel.]"
4,3,381,3_roesje_ivm_betalen_griepprik,"[roesje, ivm, betalen, griepprik, ivm crohn, crohn, waarde, entyvio, kwaad, huiverig]","[Ik heb donderdag mijn tweemaandelijks entyvio infuus gehad , voorheen heb ik nooit zulke plekken gehad Vandaar mijn vraag of het door medicatie komt of door de ziekte zelf (CU ) Ook is mijn vraag , moet ik hier even mee naar de huisarts of weet u hoe en wat ik erop mag smeren om het branden weg te nemen Alvast bedankt narinx, MDL verpleegkundigen, ik wil even laten weten dat ik een tweede terugplaatsing van een embryo heb gehad vandaag heb ik een zwangerschapstest mogen doen en ben hernieuwd zwanger , hopelijk gaat de zwangerschap deze keer goed lopen en zien we over een paar weke..."
5,4,333,4_infusie_vraag_overleg_nadelen,"[infusie, vraag, overleg, nadelen, omgaand reactie, schrijven, zaken, ter, ontvangen bevolkingsonderzoek, adviseerde contact]","[Ter info voor het overleg v.w.b., Ik heb vandaag terugkoppeling ontvangen van bevolkingsonderzoek en wordt opgeroepen voor een intake n.a.v., Ik heb vandaag terugkoppeling ontvangen van bevolkingsonderzoek en wordt opgeroepen voor een intake n.a.v.]"
6,5,329,5_buik_rug_pijn_gevoel,"[buik, rug, pijn, gevoel, krampen, onderbuik, benen, last, buikpijn, handen]","[Ik slik nu ander halve week cortiment en ik merk dat ik buikpijn heb links boven in mijn buik ter hoogte van de alvleesklier wat naar mijn rug trekt., Ik slik nu ander halve week cortiment en ik merk dat ik buikpijn heb links boven in mijn buik ter hoogte van de alvleesklier wat naar mijn rug trekt., Ik slik nu ander halve week cortiment en ik merk dat ik buikpijn heb links boven in mijn buik ter hoogte van de alvleesklier wat naar mijn rug trekt.]"
7,6,265,6_prima_wacht_helemaal prima_goed wacht,"[prima, wacht, helemaal prima, goed wacht, weet voldoende, helemaal, goed, probleem, jazeker, klopt]","[Dat is prima voor mij., Is prima, zal ik doen., Dat is prima, ik zal deze zo maken.]"
8,7,258,7_afspraak_afspraak afspraak_afspraak staan_afspraak gepland,"[afspraak, afspraak afspraak, afspraak staan, afspraak gepland, gepland, staan, staat afspraak, poli afspraak, staan afspraak, uur]","[Op 1 september staat voor mij een afspraak gepland bij ., Op staat er een afspraak gepland met ., 17/2 is n poli afspraak weer gepland.]"
9,8,254,8_gestart_ustekinumab_begonnen_gestopt,"[gestart, ustekinumab, begonnen, gestopt, bezig, waarde, calprotectine waarde, zakjes, pantazol, zetpillen]","[Ik ben afgelopen maandag met Cortiment gestart., In mijn digitale [ZIEKENHUIS] omgeving staat alleen de CRP-waarde (3,2mg/L), maar niet de calprotectine-waarde vermeld., In mijn digitale [ZIEKENHUIS] omgeving staat alleen de CRP-waarde (3,2mg/L), maar niet de calprotectine-waarde vermeld.]"

In [410]:
# Reduce outliers
topics = topic_model.topics_
new_topics = topic_model.reduce_outliers(sentences, topics)

100%|██████████| 20/20 [00:02<00:00,  8.01it/s]

In [411]:
topic_model.update_topics(sentences, topics=new_topics)

2024-11-18 22:25:40,234 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

In [44]:
topic_model.save("/workspace/mijnidbcoachnlp/data/result_data/saved_BERTje_model_reduced_outliers", serialization="pytorch", save_ctfidf=True, save_embedding_model=embedding_model)

In [391]:
loaded_model_ro = BERTopic.load("/workspace/mijnidbcoachnlp/data/result_data/saved_BERTje_model_reduced_outliers", embedding_model=embedding_model)

In [392]:
# INSPECT topics again # Looks good
topic_model = loaded_model_ro
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,240,-1_jl_topper_bent_ja,"[jl, topper, bent, ja, braakgevoel, vriendekijke, beangstigend, 09, doen, 1x]",NaN
1,0,2231,0_pijn_toilet_buikpijn_gevoel,"[pijn, toilet, buikpijn, gevoel, buik, last, veel, wc, diarree, krampen]",NaN
2,1,828,1_kunt_zouden_kunnen_sturen,"[kunt, zouden, kunnen, sturen, mij, doorgeven, jullie, willen, wilt, recept]",NaN
3,2,834,2_recept_nieuw_herhaalrecept_nethol,"[recept, nieuw, herhaalrecept, nethol, aanvragen, herhaal, puri, apotheek, pentasa, graag]",NaN
4,3,603,3_ziekenhuis_in_apotheek_naar,"[ziekenhuis, in, apotheek, naar, het, bij, gestuurd, komen, prikken, ophalen]",NaN
...,...,...,...,...,...
335,334,46,334_nachts_extreem_wakker_zondagochtend,"[nachts, extreem, wakker, zondagochtend, maagzuur, gespuugd, warm, hierdoor, borrelt, gewrichten]",NaN
336,335,46,335_voet_irritatie_gewricht_aantal,"[voet, irritatie, gewricht, aantal, sinds, heftige, donderdagavond, warmte, enkels, bepaalde]",NaN
337,336,21,336_uw_alvast_reactie_bedankt,"[uw, alvast, reactie, bedankt, antwoord, voor, advies, jullie, en, ]",NaN
338,337,49,337_calpro_test_gedaan_gluten,"[calpro, test, gedaan, gluten, calprotectine, abces, achtergelaten, ug, score, conform]",NaN
339,338,72,338_hoor_graag_jullie_hoe,"[hoor, graag, jullie, hoe, mogelijkheid, ondernemen, denken, verder, geluk, bevallen]",NaN

In [401]:
vectorizer_model=CountVectorizer(stop_words=dutch_stopwords, min_df=2, ngram_range=(1, 1), token_pattern=r'\b[a-zA-Z]{3,}\b')
topic_model.update_topics(sentences, vectorizer_model=vectorizer_model)
topic_model.get_topic_info()

KeyboardInterrupt:

In [46]:
#save the topic info
topic_info = topic_model.get_topic_info()
topic_info.to_csv('/workspace/mijnidbcoachnlp/data/result_data/topic_info_bertje.csv', index=False)

In [47]:
#save the topic info
doc_info = topic_model.get_document_info(sentences)
doc_info.to_csv('/workspace/mijnidbcoachnlp/data/result_data/doc_info_bertje.csv', index=False)

### 4.2 Merging topics with hierarchy

In [397]:
topic_model = BERTopic.load("/workspace/mijnidbcoachnlp/data/result_data/saved_BERTje_model_reduced_outliers", embedding_model=embedding_model)

In [399]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,240,-1_jl_topper_bent_ja,"[jl, topper, bent, ja, braakgevoel, vriendekijke, beangstigend, 09, doen, 1x]",NaN
1,0,2231,0_pijn_toilet_buikpijn_gevoel,"[pijn, toilet, buikpijn, gevoel, buik, last, veel, wc, diarree, krampen]",NaN
2,1,828,1_kunt_zouden_kunnen_sturen,"[kunt, zouden, kunnen, sturen, mij, doorgeven, jullie, willen, wilt, recept]",NaN
3,2,834,2_recept_nieuw_herhaalrecept_nethol,"[recept, nieuw, herhaalrecept, nethol, aanvragen, herhaal, puri, apotheek, pentasa, graag]",NaN
4,3,603,3_ziekenhuis_in_apotheek_naar,"[ziekenhuis, in, apotheek, naar, het, bij, gestuurd, komen, prikken, ophalen]",NaN
...,...,...,...,...,...
335,334,46,334_nachts_extreem_wakker_zondagochtend,"[nachts, extreem, wakker, zondagochtend, maagzuur, gespuugd, warm, hierdoor, borrelt, gewrichten]",NaN
336,335,46,335_voet_irritatie_gewricht_aantal,"[voet, irritatie, gewricht, aantal, sinds, heftige, donderdagavond, warmte, enkels, bepaalde]",NaN
337,336,21,336_uw_alvast_reactie_bedankt,"[uw, alvast, reactie, bedankt, antwoord, voor, advies, jullie, en, ]",NaN
338,337,49,337_calpro_test_gedaan_gluten,"[calpro, test, gedaan, gluten, calprotectine, abces, achtergelaten, ug, score, conform]",NaN
339,338,72,338_hoor_graag_jullie_hoe,"[hoor, graag, jullie, hoe, mogelijkheid, ondernemen, denken, verder, geluk, bevallen]",NaN

In [400]:
hierarchical_topics = topic_model.hierarchical_topics(sentences)
topic_model.visualize_hierarchy(hierarchical_topics=hierarchical_topics)

100%|██████████| 338/338 [00:02<00:00, 159.32it/s]

In [351]:
#save the topic info
topic_info = topic_model.get_topic_info()
topic_info["Name"].to_list()

['-1_bedankt_dank_reactie_hoor',
 '0_last_ontlasting_pijn_buikpijn',
 '1_afspraak_ontvangen_formulieren_mogelijk',
 '2_bloed_prikken_ontlasting_uitslag',
 '3_gebruik_humira_crohn_medicatie',
 '4_recept_apotheek_ziekenhuis_nieuw',
 '5_weet_advies_mee_beste',
 '6_afspraak_contact_uur_telefonisch',
 '7_gaat_goed_zorgen_voel',
 '8_huisarts_afspraak_coloscopie_oproep',
 '9_corona_getest_positief_covid',
 '10_scan_endoscopie_mri_onderzoek',
 '11_stress_kilo_afgevallen_eten',
 '12_zwanger_begonnen_gedaan_zwangerschapstest',
 '13_werk_meld_begin_gemeld']

In [329]:
# merge some topics
topics_to_merge = [[20, 328, 207, 301], # Diet
                    [281, 158, 278, 263, 259, 41, 13, 220], # Consultation/Hospital Visit
                    [181, 276, 243, 175, 163, 112,311, 246, 325, 216, 312, 321, 303, 306, 175, 163, 112, 188, 40, 129, 142, 204, 148], # Health Update
                    [261, 297, 190, 53, 70, 131, 171, 251, 323, 203, 225, 300, 160, 67, 111, 252, 213, 176, 258, 257, 66, 224, 162, 52, 49,
                    38, 153, 226, 152, 168, 309, 180, 104, 196, 201], # Medical Advice/Discussion
                    [192, 324, 54, 110], # Exam
                    [210, 103, 135, 106, 63, 62, 288, 113, 149, 81, 109, 92, 159, 14, 88, 332, 108, 79, 95, 134, 250, 75, 284, 169, 266, 193,
                    51, 37, 194, 72], # Medication
                    [329, 268, 215], # Pregnancy
                    [147, 86, 50, 27, 97, 260, 61, 71, 47, 326, 209, 273, 335, 182, 32, 0, 6, 105, 286, 334, 126, 227, 15, 231, 313, 293, 78, 146, 320, 270, 255, 42], # Symptoms
                    [], # Surgery
                    [197, 244, 136, 229, 154, 329, 43, 248, 302, 172], # Vaccination
                    [276, 243], # Work
                    [56, 141, 235, 191, 232, 36, 33, 265, 285, 57, 264, 179, 205, 48, 115, 94, 107, 118, 64,
                    291, 295, 236, 254, 285, 80, 22, 280, 242, 289, 59, 223, 187, 294, 282, 73, 240, 161, 25, 198, 310, 178, 316, 26, 221, 157,
                    55, 127, 24, 17, 16, 34, 5], # Admin comm (survey, patient info, documents)
                    [122, 18, 137, 144, 164, 292, 83, 87, 123, 31, 116, 10, 174, 230], # Appointment/contact
                    [3, 256, 90, 296, 2, 208, 1, 202, 84, 253, 114, 290, 315, 100, 317, 8], # Pharmacy
                    [183, 121, 165, 211, 167, 12, 21, 132, 65, 337, 89, 9, 125, 60, 28, 23, 19, 29, 68, 7, 173, 186, 304, 124], # Test
                    [239, 151, 277, 287, 222, 262, 139, 102, 85, 322, 189, 150, 234, 119, 143, 35, 338, 184, 279, 98, 44, 233, 99, 212, 331, 76, 199, 298, 247, 128,
                    336, 91, 330, 333, 138, 145, 245, 46, 58, 314, 214, 305, 166, 93, 4, 217, 117, 274, 219, 200, 69, 319, 241, 185, 267, 74, 77,
                    249, 82, 307, 177, 318, 269, 156, 195, 238, 218, 272, 155, 275, 271, 299, 228, 308, 237, 96, 206, 133, 101, 327, 170, 39, 130] # Other

]
topic_model.merge_topics(sentences, topics_to_merge)

In [403]:
doc_info = topic_model.get_document_info(sentences)
doc_info[doc_info["Topic"] == 301]

,Document,Topic,Name,Representation,Representative_Docs,Top_n_words,Representative_document
2294,Kun je dat i.i.g.,301,301_nutridrink_drink_vloeibaar_gestart,"[nutridrink, drink, vloeibaar, gestart, machtiging, middenrif, achterkant, medireva, snijdende, bijvoeding]",NaN,nutridrink - drink - vloeibaar - gestart - machtiging - middenrif - achterkant - medireva - snijdende - bijvoeding,False
4575,Ik ga nu dan ook toch weer 2 nutridrink per dag pakken ipv 1.,301,301_nutridrink_drink_vloeibaar_gestart,"[nutridrink, drink, vloeibaar, gestart, machtiging, middenrif, achterkant, medireva, snijdende, bijvoeding]",NaN,nutridrink - drink - vloeibaar - gestart - machtiging - middenrif - achterkant - medireva - snijdende - bijvoeding,False
4763,Dus kunt u a.u.b.,301,301_nutridrink_drink_vloeibaar_gestart,"[nutridrink, drink, vloeibaar, gestart, machtiging, middenrif, achterkant, medireva, snijdende, bijvoeding]",NaN,nutridrink - drink - vloeibaar - gestart - machtiging - middenrif - achterkant - medireva - snijdende - bijvoeding,False
11597,Die andere Nutridrink drink ik niet.,301,301_nutridrink_drink_vloeibaar_gestart,"[nutridrink, drink, vloeibaar, gestart, machtiging, middenrif, achterkant, medireva, snijdende, bijvoeding]",NaN,nutridrink - drink - vloeibaar - gestart - machtiging - middenrif - achterkant - medireva - snijdende - bijvoeding,False
14691,Gisteren heb ik mijn nutridrink op de sorgente website besteld.,301,301_nutridrink_drink_vloeibaar_gestart,"[nutridrink, drink, vloeibaar, gestart, machtiging, middenrif, achterkant, medireva, snijdende, bijvoeding]",NaN,nutridrink - drink - vloeibaar - gestart - machtiging - middenrif - achterkant - medireva - snijdende - bijvoeding,False
15756,Kan jullie a.u.b.,301,301_nutridrink_drink_vloeibaar_gestart,"[nutridrink, drink, vloeibaar, gestart, machtiging, middenrif, achterkant, medireva, snijdende, bijvoeding]",NaN,nutridrink - drink - vloeibaar - gestart - machtiging - middenrif - achterkant - medireva - snijdende - bijvoeding,False
15774,"en , Kunnen jullie a.u.b.",301,301_nutridrink_drink_vloeibaar_gestart,"[nutridrink, drink, vloeibaar, gestart, machtiging, middenrif, achterkant, medireva, snijdende, bijvoeding]",NaN,nutridrink - drink - vloeibaar - gestart - machtiging - middenrif - achterkant - medireva - snijdende - bijvoeding,False
20302,willen jullie a.u.b.,301,301_nutridrink_drink_vloeibaar_gestart,"[nutridrink, drink, vloeibaar, gestart, machtiging, middenrif, achterkant, medireva, snijdende, bijvoeding]",NaN,nutridrink - drink - vloeibaar - gestart - machtiging - middenrif - achterkant - medireva - snijdende - bijvoeding,False
27275,Ik heb ook echt geen zin in Nutridrink!,301,301_nutridrink_drink_vloeibaar_gestart,"[nutridrink, drink, vloeibaar, gestart, machtiging, middenrif, achterkant, medireva, snijdende, bijvoeding]",NaN,nutridrink - drink - vloeibaar - gestart - machtiging - middenrif - achterkant - medireva - snijdende - bijvoeding,False
28020,Kunnen jullie a.u.b.,301,301_nutridrink_drink_vloeibaar_gestart,"[nutridrink, drink, vloeibaar, gestart, machtiging, middenrif, achterkant, medireva, snijdende, bijvoeding]",NaN,nutridrink - drink - vloeibaar - gestart - machtiging - middenrif - achterkant - medireva - snijdende - bijvoeding,False
28024,Kunnen jullie a.u.b.,301,301_nutridrink_drink_vloeibaar_gestart,"[nutridrink, drink, vloeibaar, gestart, machtiging, middenrif, achterkant, medireva, snijdende, bijvoeding]",NaN,nutridrink - drink - vloeibaar - gestart - machtiging - middenrif - achterkant - medireva - snijdende - bijvoeding,False
28027,Kunnen jullie a.u.b.,301,301_nutridrink_drink_vloeibaar_gestart,"[nutridrink, drink, vloeibaar, gestart, machtiging, middenrif, achterkant, medireva, snijdende, bijvoeding]",NaN,nutridrink - drink - vloeibaar - gestart - machtiging - middenrif - achterkant - medireva - snijdende - bijvoeding,False
28030,Kunnen jullie a.u.b.,301,301_nutridrink_drink_vloeibaar_gestart,"[nutridrink, drink, vloeibaar, gestart, machtiging, middenrif, achterkant, medireva, snijdende, bijvoeding]",NaN,nutridrink - drink - vloeibaar - gestart - machtiging - middenrif - achterkant - medireva - snijdende - bijvoeding,False
28033,Kunnen jullie a.u.b.,301,301_nutridrink_drink_vloeibaar_gestart,"[nutridrink, drink, vloeibaar, gestart, machtiging, middenrif, achterkant, medireva, snijdende, bijvoeding]",NaN,nutridrink - drink - vloeibaar - gestart - machtiging - middenrif - achterkant - medireva - snijdende - bijvoeding,False
28057,Kunnen jullie a.u.b.,301,301_nutridrink_drink_vloeibaar_gestart,"[nutridrink, drink, vloeibaar, gestart, machtiging, middenrif, achterkant, medireva, snijdende, bijvoeding]",NaN,nutridrink - drink - vloeibaar - gestart - machtiging - middenrif - achterkant - medireva - snijdende - bijvoeding,False
28061,Kunnen jullie a.u.b.,301,301_nutridrink_drink_vloeibaar_gestart,"[nutridrink, drink, vloeibaar, gestart, machtiging, middenrif, achterkant, medireva, snijdende, bijvoeding]",NaN,nutridrink - drink - vloeibaar - gestart - machtiging - middenrif - achterkant - medireva - snijdende - bijvoeding,False
28064,Kunnen jullie het recept a.u.b.,301,301_nutridrink_drink_vloeibaar_gestart,"[nutridrink, drink, vloeibaar, gestart, machtiging, middenrif, achterkant, medireva, snijdende, bijvoeding]",NaN,nutridrink - drink - vloeibaar - gestart - machtiging - middenrif - achterkant - medireva - snijdende - bijvoeding,False
28065,Kunnen jullie a.u.b.,301,301_nutridrink_drink_vloeibaar_gestart,"[nutridrink, drink, vloeibaar, gestart, machtiging, middenrif, achterkant, medireva, snijdende, bijvoeding]",NaN,nutridrink - drink - vloeibaar - gestart - machtiging - middenrif - achterkant - medireva - snijdende - bijvoeding,False
31667,Kunt u mij z.s.m.,301,301_nutridrink_drink_vloeibaar_gestart,"[nutridrink, drink, vloeibaar, gestart, machtiging, middenrif, achterkant, medireva, snijdende, bijvoeding]",NaN,nutridrink - drink - vloeibaar - gestart - machtiging - middenrif - achterkant - medireva - snijdende - bijvoeding,False
33297,Ik drink geen nutridrink meer gezien ik zelf alles kan eten.,301,301_nutridrink_drink_vloeibaar_gestart,"[nutridrink, drink, vloeibaar, gestart, machtiging, middenrif, achterkant, medireva, snijdende, bijvoeding]",NaN,nutridrink - drink - vloeibaar - gestart - machtiging - middenrif - achterkant - medireva - snijdende - bijvoeding,False
33368,"'Eet' sinds dinsdag, op advies van de diëtiste, alleen vloeibaar met 3 nutridrink per dag, dat gaat relatief prima.",301,301_nutridrink_drink_vloeibaar_gestart,"[nutridrink, drink, vloeibaar, gestart, machtiging, middenrif, achterkant, medireva, snijdende, bijvoeding]",NaN,nutridrink - drink - vloeibaar - gestart - machtiging - middenrif - achterkant - medireva - snijdende - bijvoeding,False
34429,Is Nutridrink o.i.d.,301,301_nutridrink_drink_vloeibaar_gestart,"[nutridrink, drink, vloeibaar, gestart, machtiging, middenrif, achterkant, medireva, snijdende, bijvoeding]",NaN,nutridrink - drink - vloeibaar - gestart - machtiging - middenrif - achterkant - medireva - snijdende - bijvoeding,False
36445,Kunnen jullie a.u.b.,301,301_nutridrink_drink_vloeibaar_gestart,"[nutridrink, drink, vloeibaar, gestart, machtiging, middenrif, achterkant, medireva, snijdende, bijvoeding]",NaN,nutridrink - drink - vloeibaar - gestart - machtiging - middenrif - achterkant - medireva - snijdende - bijvoeding,False
36559,Ben toen ook terug gestart met nutridrink.,301,301_nutridrink_drink_vloeibaar_gestart,"[nutridrink, drink, vloeibaar, gestart, machtiging, middenrif, achterkant, medireva, snijdende, bijvoeding]",NaN,nutridrink - drink - vloeibaar - gestart - machtiging - middenrif - achterkant - medireva - snijdende - bijvoeding,False
36567,Ben toen ook terug gestart met nutridrink.,301,301_nutridrink_drink_vloeibaar_gestart,"[nutridrink, drink, vloeibaar, gestart, machtiging, middenrif, achterkant, medireva, snijdende, bijvoeding]",NaN,nutridrink - drink - vloeibaar - gestart - machtiging - middenrif - achterkant - medireva - snijdende - bijvoeding,False
36575,Ben toen ook terug gestart met nutridrink.,301,301_nutridrink_drink_vloeibaar_gestart,"[nutridrink, drink, vloeibaar, gestart, machtiging, middenrif, achterkant, medireva, snijdende, bijvoeding]",NaN,nutridrink - drink - vloeibaar - gestart - machtiging - middenrif - achterkant - medireva - snijdende - bijvoeding,False
36583,Ben toen ook terug gestart met nutridrink.,301,301_nutridrink_drink_vloeibaar_gestart,"[nutridrink, drink, vloeibaar, gestart, machtiging, middenrif, achterkant, medireva, snijdende, bijvoeding]",NaN,nutridrink - drink - vloeibaar - gestart - machtiging - middenrif - achterkant - medireva - snijdende - bijvoeding,False
37313,"graag zou ik willen weten of de machtiging bij medireva voor de bijvoeding (nutridrink)die ik heb gehad nog geld en of t mogelijk is om een nieuwe machtiging aan te vragen aangezien ik blijf afvallen en van de 63 kg die ik eerst woog ik nu nog maar 56,4 kg ben.",301,301_nutridrink_drink_vloeibaar_gestart,"[nutridrink, drink, vloeibaar, gestart, machtiging, middenrif, achterkant, medireva, snijdende, bijvoeding]",NaN,nutridrink - drink - vloeibaar - gestart - machtiging - middenrif - achterkant - medireva - snijdende - bijvoeding,False
37766,"Drink al weken nutridrink en eet beetje vloeibaar en drink elke avond zakje movicolon..maar ben vannacht naar huisartsenpost moeten gaan met snijdende aanhoudende pijn in middenrif, dat uitstraalt naar achterkant tussen schouderbladen.",301,301_nutridrink_drink_vloeibaar_gestart,"[nutridrink, drink, vloeibaar, gestart, machtiging, middenrif, achterkant, medireva, snijdende, bijvoeding]",NaN,nutridrink - drink - vloeibaar - gestart - machtiging - middenrif - achterkant - medireva - snijdende - bijvoeding,False
41171,Kunnen jullie a.u.b.,301,301_nutridrink_drink_vloeibaar_gestart,"[nutridrink, drink, vloeibaar, gestart, machtiging, middenrif, achterkant, medireva, snijdende, bijvoeding]",NaN,nutridrink - drink - vloeibaar - gestart - machtiging - middenrif - achterkant - medireva - snijdende - bijvoeding,False
41173,Kunnen jullie a.u.b.,301,301_nutridrink_drink_vloeibaar_gestart,"[nutridrink, drink, vloeibaar, gestart, machtiging, middenrif, achterkant, medireva, snijdende, bijvoeding]",NaN,nutridrink - drink - vloeibaar - gestart - machtiging - middenrif - achterkant - medireva - snijdende - bijvoeding,False
41178,Kunnen jullie a.u.b.,301,301_nutridrink_drink_vloeibaar_gestart,"[nutridrink, drink, vloeibaar, gestart, machtiging, middenrif, achterkant, medireva, snijdende, bijvoeding]",NaN,nutridrink - drink - vloeibaar - gestart - machtiging - middenrif - achterkant - medireva - snijdende - bijvoeding,False
41180,Kunnen jullie a.u.b.,301,301_nutridrink_drink_vloeibaar_gestart,"[nutridrink, drink, vloeibaar, gestart, machtiging, middenrif, achterkant, medireva, snijdende, bijvoeding]",NaN,nutridrink - drink - vloeibaar - gestart - machtiging - middenrif - achterkant - medireva - snijdende - bijvoeding,False
41183,Kunnen jullie a.u.b.,301,301_nutridrink_drink_vloeibaar_gestart,"[nutridrink, drink, vloeibaar, gestart, machtiging, middenrif, achterkant, medireva, snijdende, bijvoeding]",NaN,nutridrink - drink - vloeibaar - gestart - machtiging - middenrif - achterkant - medireva - snijdende - bijvoeding,False
41293,Kunnen jullie deze mij a.u.b.,301,301_nutridrink_drink_vloeibaar_gestart,"[nutridrink, drink, vloeibaar, gestart, machtiging, middenrif, achterkant, medireva, snijdende, bijvoeding]",NaN,nutridrink - drink - vloeibaar - gestart - machtiging - middenrif - achterkant - medireva - snijdende - bijvoeding,False

In [350]:

# merge some topics
topics_to_merge = [[2, 12]
]
topic_model.merge_topics(sentences, topics_to_merge)

In [347]:
# Manually Put Labels in the Label Column
# Create the customized label column
topic_info["Label"] = None

In [352]:
topic_info.to_excel('/workspace/mijnidbcoachnlp/data/result_data/final_topic_info_bertje.xlsx', index=False)

In [353]:
labeled_topic_info = pd.read_excel('/workspace/mijnidbcoachnlp/data/result_data/merged_topic_info_bertje_labeled.xlsx')

In [360]:
labeled_topic_info.rename(columns={"Unnamed: 5": "Model_Label"}, inplace=True)

In [354]:
merged_doc_info = topic_model.get_document_info(sentences)
merged_doc_info.to_excel('/workspace/mijnidbcoachnlp/data/result_data/merged_doc_info_bertje.xlsx', index=False)

In [355]:
merged_doc_info["Sentence_ID"] = merged_doc_info.index

In [356]:
annotated_df['Sentence_ID'] = annotated_df['Sentence_ID'].astype(str)
merged_doc_info['Sentence_ID'] = merged_doc_info['Sentence_ID'].astype(str)

In [385]:
# Now perform the merge
annotated_df = pd.merge(
    annotated_df,
    merged_doc_info[['Sentence_ID', 'Topic', 'Top_n_words']],
    on='Sentence_ID',
    how='left'
)

ValueError: You are trying to merge on int64 and object columns. If you wish to proceed you should use pd.concat

In [362]:
annotated_df = pd.merge(
    annotated_df,
    labeled_topic_info[['Topic', 'Model_Label']],
    on='Topic',
    how='left'
)

In [378]:
# Filter the DataFrame for manual labels equal to "A4"
label = "M7"
test_df = annotated_df[annotated_df["Manual_Label"] == label]

# Calculate the accuracy as the percentage of matches
accuracy = (test_df['Manual_Label'] == test_df['Model_Label']).sum() / len(test_df)

# Output the accuracy
print(f"Accuracy for Manual_Label == {label}: {accuracy * 100:.2f}%")

Accuracy for Manual_Label == M7: 0.00%