# Data Cleaning (Start From Here)

In [1]:
# read the original anonymized dataframe
import pandas as pd
df = pd.read_excel("/workspace/mijnidbcoachnlp/data/analysis_data/anonymized_berichten.xlsx")

In [2]:
len(set(df["UserGUID"].iloc[2:].to_list()))

856

In [3]:
len(df[["Message"]][2:]) # Number of messages = 33237

33237

In [4]:
len(df["Message"][df["richting (van of naar cliënt)"] == 'From client'])
# number of messages sent from patients = 13199

13199

### Step 1. Remove html tags from the messages

In [5]:
# clean up the html tags
from bs4 import BeautifulSoup
def clean_html_with_soup(text):
    soup = BeautifulSoup(text, 'html.parser')
    return soup.get_text()

df['Message'] = df['Message'].apply(lambda x: clean_html_with_soup(str(x)))

/tmp/ipykernel_376483/1416969809.py:4: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  soup = BeautifulSoup(text, 'html.parser')

In [6]:
df=df[2:]

In [7]:
df = df.reset_index()
df["Message_ID"] = df.index
df=df.drop(columns=["index"])
df

,ProviderName,ProgramName,UserGUID,Datum/tijd,Message,richting (van of naar cliënt),Verzender indien naar cliënt,Message_ID
0,MUMC MijnIBDcoach,MijnIBDcoach4.0,72BF6AE2-1568-4843-A234-51A9F5598B80,2020-01-14 16:34:16.323,"Goedemiddag, Dank voor uw aanmelding en het i...",To client,miacilissen,0
1,MUMC MijnIBDcoach,MijnIBDcoach4.0,72BF6AE2-1568-4843-A234-51A9F5598B80,2020-02-10 12:46:36.230,"Beste gebruikers van mijnIBDcoach, Van 11 fe...",To client,isour1_mumc,1
2,MUMC MijnIBDcoach,MijnIBDcoach4.0,72BF6AE2-1568-4843-A234-51A9F5598B80,2020-03-02 08:38:01.253,"Beste gebruiker van mijnIBDcoach, In verband...",To client,isour1_mumc,2
3,MUMC MijnIBDcoach,MijnIBDcoach4.0,72BF6AE2-1568-4843-A234-51A9F5598B80,2020-07-28 15:49:29.733,Ik ben 2 weken geleden met spoed opgenomen in ...,From client,NaN,3
4,MUMC MijnIBDcoach,MijnIBDcoach4.0,72BF6AE2-1568-4843-A234-51A9F5598B80,2020-07-28 16:23:42.457,"Goedemiddag, Bedankt voor uw bericht. We zul...",To client,isour1_mumc,4
...,...,...,...,...,...,...,...,...
33232,MUMC MijnIBDcoach,MijnIBDcoach5.0,BC3E4A89-8869-4663-9240-0A7C8FE5C008,2021-11-04 15:17:48.923,A.U.B. NIET REAGEREN OP DIT BERICHT Beste geb...,To client,mumcibd_support,33232
33233,MUMC MijnIBDcoach,MijnIBDcoach5.0,BC3E4A89-8869-4663-9240-0A7C8FE5C008,2021-11-22 14:01:17.450,A.U.B. NIET REAGEREN OP DIT BERICHT Beste geb...,To client,isour1_mumc,33233
33234,MUMC MijnIBDcoach,MijnIBDcoach5.0,BC3E4A89-8869-4663-9240-0A7C8FE5C008,2022-01-11 11:35:02.663,AUB NIET REAGEREN OP DIT BERICHT Beste gebrui...,To client,mumcibd_support,33234
33235,MUMC MijnIBDcoach,MijnIBDcoach5.0,BC3E4A89-8869-4663-9240-0A7C8FE5C008,2022-04-11 18:13:23.077,VRAGENLIJST FACTOREN UIT HET DAGELIJKSE LEVEN...,To client,mpierik_mumc,33235
33236,MUMC MijnIBDcoach,MijnIBDcoach5.0,BC3E4A89-8869-4663-9240-0A7C8FE5C008,2022-05-17 12:22:41.187,"Dag,Uit onderzoek blijkt dat bepaalde factoren...",To client,miacilissen,33236

In [8]:
column_to_move = 'Message_ID'
new_column_order = [column_to_move] + [col for col in df.columns if col != column_to_move]

# Reorder the DataFrame columns
df = df[new_column_order]
df.to_excel("/workspace/mijnidbcoachnlp/data/analysis_data/message_data.xlsx")
df

,Message_ID,ProviderName,ProgramName,UserGUID,Datum/tijd,Message,richting (van of naar cliënt),Verzender indien naar cliënt
0,0,MUMC MijnIBDcoach,MijnIBDcoach4.0,72BF6AE2-1568-4843-A234-51A9F5598B80,2020-01-14 16:34:16.323,"Goedemiddag, Dank voor uw aanmelding en het i...",To client,miacilissen
1,1,MUMC MijnIBDcoach,MijnIBDcoach4.0,72BF6AE2-1568-4843-A234-51A9F5598B80,2020-02-10 12:46:36.230,"Beste gebruikers van mijnIBDcoach, Van 11 fe...",To client,isour1_mumc
2,2,MUMC MijnIBDcoach,MijnIBDcoach4.0,72BF6AE2-1568-4843-A234-51A9F5598B80,2020-03-02 08:38:01.253,"Beste gebruiker van mijnIBDcoach, In verband...",To client,isour1_mumc
3,3,MUMC MijnIBDcoach,MijnIBDcoach4.0,72BF6AE2-1568-4843-A234-51A9F5598B80,2020-07-28 15:49:29.733,Ik ben 2 weken geleden met spoed opgenomen in ...,From client,NaN
4,4,MUMC MijnIBDcoach,MijnIBDcoach4.0,72BF6AE2-1568-4843-A234-51A9F5598B80,2020-07-28 16:23:42.457,"Goedemiddag, Bedankt voor uw bericht. We zul...",To client,isour1_mumc
...,...,...,...,...,...,...,...,...
33232,33232,MUMC MijnIBDcoach,MijnIBDcoach5.0,BC3E4A89-8869-4663-9240-0A7C8FE5C008,2021-11-04 15:17:48.923,A.U.B. NIET REAGEREN OP DIT BERICHT Beste geb...,To client,mumcibd_support
33233,33233,MUMC MijnIBDcoach,MijnIBDcoach5.0,BC3E4A89-8869-4663-9240-0A7C8FE5C008,2021-11-22 14:01:17.450,A.U.B. NIET REAGEREN OP DIT BERICHT Beste geb...,To client,isour1_mumc
33234,33234,MUMC MijnIBDcoach,MijnIBDcoach5.0,BC3E4A89-8869-4663-9240-0A7C8FE5C008,2022-01-11 11:35:02.663,AUB NIET REAGEREN OP DIT BERICHT Beste gebrui...,To client,mumcibd_support
33235,33235,MUMC MijnIBDcoach,MijnIBDcoach5.0,BC3E4A89-8869-4663-9240-0A7C8FE5C008,2022-04-11 18:13:23.077,VRAGENLIJST FACTOREN UIT HET DAGELIJKSE LEVEN...,To client,mpierik_mumc
33236,33236,MUMC MijnIBDcoach,MijnIBDcoach5.0,BC3E4A89-8869-4663-9240-0A7C8FE5C008,2022-05-17 12:22:41.187,"Dag,Uit onderzoek blijkt dat bepaalde factoren...",To client,miacilissen

### Step 2. Split the message into sentences

In [14]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [15]:
# using nltk instead of spacy
import nltk
from nltk.tokenize import sent_tokenize
import re

def split_sentence_with_matches(sentence, matches):
    
    
    parts = []
    for i in range(len(matches)):
        match = matches[i]
        part = sentence.split(match, 1)[0]
        
        if i > 0:
            part = "".join([matches[i-1], part])
        
        parts.append(part)
        remaining_part = sentence.split(match, 1)[1]
        sentence = remaining_part
    
    if remaining_part:
        part = "".join([matches[-1], remaining_part])
        parts.append(part)

    return parts


def split_sentence(sentence):
    pattern1 = r'(?<!^)Maar|En|Ik|Ze|Het'
    pattern2 = r'(?<!^)\.\s*[A-Z][a-z]+'
    matches1 = re.findall(pattern1, sentence)
    matches2 = re.findall(pattern2, sentence)
    matches = matches1
    if len(matches1) < len(matches2):
        matches = matches2
    smaller_sentences = []
    if matches:
        smaller_sentences = split_sentence_with_matches(sentence, matches)
    else:
        #print("Can't split the following sentence: ", "\n", sentence)
        pass
    return smaller_sentences


def nltk_split_into_sentences(df, column):
    sentence_data = []
    
    # Loop through each message in the original DataFrame
    for message_id, message in zip(df['Message_ID'], df[column]):
        sentences = sent_tokenize(message)
            
        # Append each sentence along with its existing Message_ID
        for sentence in sentences:
            
            sentence = sentence.strip()
            if len(sentence) <= 400 or 'voedinginformatie' in sentence.lower():
                sentence_data.append({'Message_ID': message_id, 'Sentence': sentence})

            else:
                #print("\nOriginal: ", "\n", sentence, "\n")
                # Call split_sentence to get smaller sentences
                smaller_sentences = split_sentence(sentence)
                
                if smaller_sentences:                    
                    for smaller_sentence in smaller_sentences:
                        smaller_sentence = re.sub(r"^[,!.?\]]*\s*", "", smaller_sentence)

                        sentence_data.append({'Message_ID': message_id, 'Sentence': smaller_sentence})

                else:
                    pass
            

    # Create a new DataFrame with the split sentences
    sentence_df = pd.DataFrame(sentence_data)

    return sentence_df

# Example usage
df_fromclient = df[df["richting (van of naar cliënt)"] == "From client"]
sentence_df_nltk = nltk_split_into_sentences(df_fromclient, column="Message")

In [16]:
sentence_df = sentence_df_nltk
sentence_df

       Message_ID                                           Sentence
0               3  Ik ben 2 weken geleden met spoed opgenomen in ...
1               3  Ik kreeg acuut een pijnlijke druk op de borst,...
2               3                  Het begon 1 uur na het avondeten.
3               3  Ik had al de hele dag migraine, had dus ook we...
4               3  Ik werd heel erg misselijk, braakneigingen, du...
...           ...                                                ...
55260       33229  Afgelopen jaren is er al vaker bloed in mijn u...
55261       33229                   Wat adviseert u hiermee te doen?
55262       33231  Hoi [PERSOON-1], Oke, dat is iig al een gerust...
55263       33231                  Dankjewel voor de snelle reactie!
55264       33231                               Groeten, [PERSOON-2]

[55265 rows x 2 columns]

### Step 2. Clean up the sentences

In [17]:
import re

def replace_numbered_patterns(text):
    text = re.sub(r'\[(\w+)-\d+\]', r'[\1]', text, flags=re.IGNORECASE)
    # Match any pattern of the form [WORD-<number>] and replace with [WORD]
    return text

# Apply the function
sentence_df['Sentence'] = sentence_df['Sentence'].apply(lambda x: replace_numbered_patterns(str(x)))

In [18]:
import re

def replace_entities(text): # notice that we did not remove anonymized entities such as [APOTHEEK] and [ZIEKENHUIS] which can be informative
    text = re.sub(r'\[persoon\]', '', text, flags=re.IGNORECASE)
    text = re.sub(r'\[locatie\]', '', text, flags=re.IGNORECASE)
    text = re.sub(r'\[url\]', '', text, flags=re.IGNORECASE)
    text = re.sub(r'\[telefoonnummer\]', '', text, flags=re.IGNORECASE)
    text = re.sub(r'\[emailadres\]', '', text, flags=re.IGNORECASE)
    text = re.sub(r'\[datum\]', '', text, flags=re.IGNORECASE)
    # remove words in the pattern of [word] but [hospital] and [pharmacy] are kept
    # remove punctuations again
    text = re.sub(r"^[,!.?\]]*\s*", '', text)
    return text

sentence_df['Clean_Sentence'] = sentence_df['Sentence'].apply(lambda x: replace_entities(str(x)))

In [19]:
## clean up greetings and closings in the messages
import re

greetings_pattern = r"^\s*(beste|geachte|dear|hallo|hoi|hoi hoi|goedemorgen|goede morgen|goedemiddag|goede middag|goeden avond|goedenavond|dag|hello|hi|morning|good morning|good afternoon|good evening)\s*[,!?.]*\s*"
signoffs_pattern = r"\b(best regards|regards|groe?t|groe?ten|gr|groetjes?|grtjs?|mvg|m?e?t?\s*vriendelijke?\s*gr\w*|met\s*vriendelijke?|hartelijke\s*gr\w*)\b\s*[,!?.]*\s*"
leading_punctuations_pattern = r"^[,!.?\]]*\s*"

def remove_greetings(text, pattern1, pattern2, pattern3):
    # Remove greetings from the beginning
    cleaned_text = re.sub(pattern1, '', text, flags=re.IGNORECASE)
    # Remove signoffs from the end
    cleaned_text = re.sub(pattern2, '', cleaned_text, flags=re.IGNORECASE)
    # Strip any leading or trailing whitespace left over after substitutions
    cleaned_text = re.sub(pattern3, '', cleaned_text)
    return cleaned_text.strip()

clean_sentences = [
    remove_greetings(msg, greetings_pattern, signoffs_pattern, leading_punctuations_pattern) 
    for msg in sentence_df["Clean_Sentence"].to_list()
]

sentence_df["Clean_Sentence"] = clean_sentences

In [20]:
# remove sentences <=15 char after cleaning
sentence_df = sentence_df[sentence_df["Clean_Sentence"].str.len() > 15]

In [39]:
sentence_df[sentence_df["Clean_Sentence"].str.contains("a.u.b.")]

,Message_ID,Sentence,Clean_Sentence
2375,1405,Zou mij deze a.u.b kunnen sturen.,Zou mij deze a.u.b kunnen sturen.
2403,1426,kan u a.u.b aan dokter [PERSOON] kunnen vrag...,kan u a.u.b aan dokter kunnen vragen of ik ...
2525,1522,ik vraag of mijn a.u.b willen bellen en laten ...,ik vraag of mijn a.u.b willen bellen en laten ...
6148,3490,Dus kunt u a.u.b.,Dus kunt u a.u.b.
6180,3505,"Goedendag, Kunt u a.u.b.","Goedendag, Kunt u a.u.b."
6328,3594,Graag naar eerlijkheid een beoordeling melden ...,Graag naar eerlijkheid een beoordeling melden ...
6556,3669,Bij het uitschrijven van de Esomeprazal a.u.b.,Bij het uitschrijven van de Esomeprazal a.u.b.
6621,3695,"Geachte heer, mevrouw, Daar mijn huisarts nie...","heer, mevrouw, Daar mijn huisarts niet de vol..."
13850,7632,"Mocht je dit maandag lezen, kun je dan a.u.b.","Mocht je dit maandag lezen, kun je dan a.u.b."
13901,7640,Kun je me daarvan de waardes vertellen a.u.b.?,Kun je me daarvan de waardes vertellen a.u.b.?
13905,7642,Kun je me het cijfer van de CRP nog geven a.u.b.?,Kun je me het cijfer van de CRP nog geven a.u.b.?
13942,7649,Laten jullie mij ook het crp getal weer weten ...,Laten jullie mij ook het crp getal weer weten ...
14077,7685,Wil je dit a.u.b.,Wil je dit a.u.b.
20619,11388,Kan jullie a.u.b.,Kan jullie a.u.b.
20646,11403,"Beste [PERSOON] en [PERSOON], Kunnen jullie a...","en , Kunnen jullie a.u.b."
26518,14726,"Hallo, willen jullie a.u.b.",willen jullie a.u.b.
34920,19658,"Morgen, Kunnen jullie mij a.u.b.","Morgen, Kunnen jullie mij a.u.b."
36563,20589,Kunnen jullie a.u.b.,Kunnen jullie a.u.b.
36567,20591,Kunnen jullie a.u.b.,Kunnen jullie a.u.b.
36571,20592,Kunnen jullie a.u.b.,Kunnen jullie a.u.b.
36575,20596,Kunnen jullie a.u.b.,Kunnen jullie a.u.b.
36579,20597,Kunnen jullie a.u.b.,Kunnen jullie a.u.b.
36609,20613,Kunnen jullie a.u.b.,Kunnen jullie a.u.b.
36615,20617,Kunnen jullie a.u.b.,Kunnen jullie a.u.b.
36620,20618,Kunnen jullie het recept a.u.b.,Kunnen jullie het recept a.u.b.
36624,20620,Kunnen jullie a.u.b.,Kunnen jullie a.u.b.
45482,25887,"Goedemorgen, sorry, ja a.u.b., mvrgr, [PERSOON]","sorry, ja a.u.b., mvrgr,"
45494,25897,"Goedemorgen [PERSOON], [PERSON], Kunt u a.u.b.","[PERSON], Kunt u a.u.b."
47431,27249,Kunnen jullie a.u.b.,Kunnen jullie a.u.b.
47451,27255,Kunt u dat doorgeven aan dokter [PERSOON] a.u.b.?,Kunt u dat doorgeven aan dokter a.u.b.?
47640,27347,Zouden jullie eens willen kijken of de uitslag...,Zouden jullie eens willen kijken of de uitslag...
53504,31827,Kunnen jullie a.u.b.,Kunnen jullie a.u.b.
53507,31829,Kunnen jullie a.u.b.,Kunnen jullie a.u.b.
53513,31834,Kunnen jullie a.u.b.,Kunnen jullie a.u.b.
53516,31838,Kunnen jullie a.u.b.,Kunnen jullie a.u.b.
53521,31841,Kunnen jullie a.u.b.,Kunnen jullie a.u.b.
53666,31988,Kunnen jullie deze mij a.u.b.,Kunnen jullie deze mij a.u.b.

In [44]:
# save df
sentence_df.to_excel("/workspace/mijnidbcoachnlp/data/analysis_data/sentence_data_before_merging.xlsx")

### Run the translate_sentences script before continuing

In [94]:
translated_sentence_df = pd.read_excel("/workspace/mijnidbcoachnlp/data/analysis_data/translated_sentence_data_before_merging.xlsx")

In [87]:
translated_sentence_df.head()

,Message_ID,Sentence,Clean_Sentence,Translated_Sentence
0,3,Ik ben 2 weken geleden met spoed opgenomen in ...,Ik ben 2 weken geleden met spoed opgenomen in ...,I was rushed into the [PRESSION] two weeks ago...
1,3,"Ik kreeg acuut een pijnlijke druk op de borst,...","Ik kreeg acuut een pijnlijke druk op de borst,...",I was acutely under a painful pressure on the ...
2,3,Het begon 1 uur na het avondeten.,Het begon 1 uur na het avondeten.,It started 1 hour after dinner.
3,3,"Ik had al de hele dag migraine, had dus ook we...","Ik had al de hele dag migraine, had dus ook we...","I had migraines all day, so I hadn't eaten much."
4,3,"Ik werd heel erg misselijk, braakneigingen, du...","Ik werd heel erg misselijk, braakneigingen, du...","I got very nauseous, vomiting, dizzy and rejuv..."

In [88]:
len(sentence_df)

42723

In [89]:
# find sentences ending in ""
abbreviation_pattern = r"\b[a-zA-Z]\.[a-zA-Z]\.[a-zA-Z]\.\s*$"

In [95]:
translated_sentence_df = translated_sentence_df.reset_index(drop=True)

In [96]:
to_drop = []
for i, row in translated_sentence_df[:-1].iterrows():
    sentence = row["Clean_Sentence"]
    if re.search(abbreviation_pattern, sentence, flags=re.IGNORECASE):
        translated_sentence_df.loc[i, "Clean_Sentence"] += " " + translated_sentence_df.loc[i + 1, "Clean_Sentence"]
        translated_sentence_df.loc[i, "Sentence"] += " " + translated_sentence_df.loc[i + 1, "Sentence"]
        translated_sentence_df.loc[i, "Translated_Sentence"] += " " + translated_sentence_df.loc[i + 1, "Translated_Sentence"]
        to_drop.append(i + 1)

# Drop merged sentences from DataFrame
translated_sentence_df.drop(to_drop, inplace=True)

# Reset index
translated_sentence_df.reset_index(drop=True, inplace=True)

In [97]:
translated_sentence_df

,Message_ID,Sentence,Clean_Sentence,Translated_Sentence
0,3,Ik ben 2 weken geleden met spoed opgenomen in ...,Ik ben 2 weken geleden met spoed opgenomen in ...,I was rushed into the [PRESSION] two weeks ago...
1,3,"Ik kreeg acuut een pijnlijke druk op de borst,...","Ik kreeg acuut een pijnlijke druk op de borst,...",I was acutely under a painful pressure on the ...
2,3,Het begon 1 uur na het avondeten.,Het begon 1 uur na het avondeten.,It started 1 hour after dinner.
3,3,"Ik had al de hele dag migraine, had dus ook we...","Ik had al de hele dag migraine, had dus ook we...","I had migraines all day, so I hadn't eaten much."
4,3,"Ik werd heel erg misselijk, braakneigingen, du...","Ik werd heel erg misselijk, braakneigingen, du...","I got very nauseous, vomiting, dizzy and rejuv..."
...,...,...,...,...
42359,33229,"Ze hebben de urine op kweek gezet, kan morgenv...","Ze hebben de urine op kweek gezet, kan morgenv...","They've put the urine on culture, can get the ..."
42360,33229,Afgelopen jaren is er al vaker bloed in mijn u...,Afgelopen jaren is er al vaker bloed in mijn u...,"In recent years, blood has been found in my ur..."
42361,33229,Wat adviseert u hiermee te doen?,Wat adviseert u hiermee te doen?,What do you suggest you do with this?
42362,33231,"Hoi [PERSOON], Oke, dat is iig al een gerustst...","Oke, dat is iig al een geruststelling ;) ik wa...","Hi [PRESSON], Okay, that's a relief;) I'll wai..."
42363,33231,Dankjewel voor de snelle reactie!,Dankjewel voor de snelle reactie!,Thank you for the quick response!

In [98]:
# drop duplicates
translated_sentence_df = translated_sentence_df.drop_duplicates(subset=["Clean_Sentence"], keep="first")  # or keep="last" or keep=False

In [99]:
# assign an ID to each of the 42537 sentence 
translated_sentence_df = translated_sentence_df.reset_index()
translated_sentence_df["Sentence_ID"] = translated_sentence_df.index + 1

In [100]:
translated_sentence_df = translated_sentence_df.drop(columns=["index"])
translated_sentence_df

,Message_ID,Sentence,Clean_Sentence,Translated_Sentence,Sentence_ID
0,3,Ik ben 2 weken geleden met spoed opgenomen in ...,Ik ben 2 weken geleden met spoed opgenomen in ...,I was rushed into the [PRESSION] two weeks ago...,1
1,3,"Ik kreeg acuut een pijnlijke druk op de borst,...","Ik kreeg acuut een pijnlijke druk op de borst,...",I was acutely under a painful pressure on the ...,2
2,3,Het begon 1 uur na het avondeten.,Het begon 1 uur na het avondeten.,It started 1 hour after dinner.,3
3,3,"Ik had al de hele dag migraine, had dus ook we...","Ik had al de hele dag migraine, had dus ook we...","I had migraines all day, so I hadn't eaten much.",4
4,3,"Ik werd heel erg misselijk, braakneigingen, du...","Ik werd heel erg misselijk, braakneigingen, du...","I got very nauseous, vomiting, dizzy and rejuv...",5
...,...,...,...,...,...
39403,33229,Ben vanmorgen urine laten controleren bij de h...,Ben vanmorgen urine laten controleren bij de h...,"I had urine checked by the GP this morning, co...",39404
39404,33229,"Ze hebben de urine op kweek gezet, kan morgenv...","Ze hebben de urine op kweek gezet, kan morgenv...","They've put the urine on culture, can get the ...",39405
39405,33229,Afgelopen jaren is er al vaker bloed in mijn u...,Afgelopen jaren is er al vaker bloed in mijn u...,"In recent years, blood has been found in my ur...",39406
39406,33229,Wat adviseert u hiermee te doen?,Wat adviseert u hiermee te doen?,What do you suggest you do with this?,39407
39407,33231,"Hoi [PERSOON], Oke, dat is iig al een gerustst...","Oke, dat is iig al een geruststelling ;) ik wa...","Hi [PRESSON], Okay, that's a relief;) I'll wai...",39408

In [55]:
# save df
translated_sentence_df.to_excel("/workspace/mijnidbcoachnlp/data/analysis_data/sentence_data_new.xlsx")