In [20]:
import pandas as pd
# Import two df
doc_info = pd.read_csv("/workspace/mijnidbcoachnlp/data/result_data/doc_info_st.csv")
doc_info_merged = pd.read_csv("/workspace/mijnidbcoachnlp/data/result_data/doc_info_st_merged.csv")

In [24]:
doc_info

,Document,Topic,Name,Representation,Representative_Docs,Top_n_words,Probability,Representative_document
0,Ik ben 2 weken geleden met spoed opgenomen in ...,8,8_ruim_aantal_infuus_last,"['ruim', 'aantal', 'infuus', 'last', 'laatste'...","['Heb al een twee weken weer last.', 'Nu over ...",ruim - aantal - infuus - last - laatste - humi...,0.951453,False
1,"Ik kreeg acuut een pijnlijke druk op de borst,...",271,271_druk_druk borst_handen_borst,"['druk', 'druk borst', 'handen', 'borst', 'lin...",['Gisteren om 22.00 uur voel ik flinke pijnlik...,druk - druk borst - handen - borst - linkerkan...,0.000000,False
2,Het begon 1 uur na het avondeten.,27,27_nacht_slaap_avond_wakker,"['nacht', 'slaap', 'avond', 'wakker', 'vannach...","['Daarnaast slaap ik de ene nacht heel vast, a...",nacht - slaap - avond - wakker - vannacht - sl...,0.000000,False
3,"Ik had al de hele dag migraine, had dus ook we...",78,78_hele_ochtend_hele bereikbaar_morgens,"['hele', 'ochtend', 'hele bereikbaar', 'morgen...","['Hele fijne dag gewenst.', 'Hele fijne dag ge...",hele - ochtend - hele bereikbaar - morgens - f...,0.000000,False
4,"Ik werd heel erg misselijk, braakneigingen, du...",3,3_pijn_buikpijn_hoofdpijn_pijnlijk,"['pijn', 'buikpijn', 'hoofdpijn', 'pijnlijk', ...","['Pijn is al wat minder.', 'Maar ik heb af en ...",pijn - buikpijn - hoofdpijn - pijnlijk - buik ...,0.984323,False
...,...,...,...,...,...,...,...,...
42532,"Ze hebben de urine op kweek gezet, kan morgenv...",0,0_bloed_prikken_bloed laten_laten prikken,"['bloed', 'prikken', 'bloed laten', 'laten pri...",['Op heb ik bloed laten prikken en ontlasting...,bloed - prikken - bloed laten - laten prikken ...,0.687659,False
42533,Afgelopen jaren is er al vaker bloed in mijn u...,0,0_bloed_prikken_bloed laten_laten prikken,"['bloed', 'prikken', 'bloed laten', 'laten pri...",['Op heb ik bloed laten prikken en ontlasting...,bloed - prikken - bloed laten - laten prikken ...,1.000000,False
42534,Wat adviseert u hiermee te doen?,253,253_hieraan_raden_adviseren_adviseert,"['hieraan', 'raden', 'adviseren', 'adviseert',...",['Wat adviseren jullie me verder nog te doen?'...,hieraan - raden - adviseren - adviseert - oorz...,1.000000,False
42535,"Oke, dat is iig al een geruststelling ;) ik wa...",11,11_hoop_wacht_wachten_afwachten,"['hoop', 'wacht', 'wachten', 'afwachten', 'hop...","['Dat is goed, dan wacht ik het even af!', 'Da...",hoop - wacht - wachten - afwachten - hopelijk ...,0.984811,False
42536,Dankjewel voor de snelle reactie!,105,105_snelle_snelle reactie_dank snelle_bedankt ...,"['snelle', 'snelle reactie', 'dank snelle', 'b...","['Bedankt voor de snelle reactie!', 'bedankt v...",snelle - snelle reactie - dank snelle - bedank...,0.861606,False

In [23]:
doc_info_merged

,Document,Topic,Name,Representation,Representative_Docs,Top_n_words,Probability,Representative_document
0,Ik ben 2 weken geleden met spoed opgenomen in ...,4,4_voel_goed_beter_gaat,"['voel', 'goed', 'beter', 'gaat', 'vorige', 'j...","['Dus dat is goed.', 'Ik voel mij redelijk goe...",voel - goed - beter - gaat - vorige - jaar - l...,0.951453,False
1,"Ik kreeg acuut een pijnlijke druk op de borst,...",2,2_pijn_last_buikpijn_klachten,"['pijn', 'last', 'buikpijn', 'klachten', 'toil...",['Verder eigenlijk geen last van buikpijn geha...,pijn - last - buikpijn - klachten - toilet - c...,0.000000,False
2,Het begon 1 uur na het avondeten.,2,2_pijn_last_buikpijn_klachten,"['pijn', 'last', 'buikpijn', 'klachten', 'toil...",['Verder eigenlijk geen last van buikpijn geha...,pijn - last - buikpijn - klachten - toilet - c...,0.000000,False
3,"Ik had al de hele dag migraine, had dus ook we...",1,1_afspraak_contact_telefonisch_vandaag,"['afspraak', 'contact', 'telefonisch', 'vandaa...","['9 Mei afspraak bij Dr,', 'afspraak is inmidd...",afspraak - contact - telefonisch - vandaag - m...,0.000000,False
4,"Ik werd heel erg misselijk, braakneigingen, du...",2,2_pijn_last_buikpijn_klachten,"['pijn', 'last', 'buikpijn', 'klachten', 'toil...",['Verder eigenlijk geen last van buikpijn geha...,pijn - last - buikpijn - klachten - toilet - c...,0.984323,False
...,...,...,...,...,...,...,...,...
42532,"Ze hebben de urine op kweek gezet, kan morgenv...",0,0_bloed_ontlasting_prikken_laten,"['bloed', 'ontlasting', 'prikken', 'laten', 'b...",['ik heb ongeveer 2 weken geleden bloed laten...,bloed - ontlasting - prikken - laten - bloed l...,0.687659,False
42533,Afgelopen jaren is er al vaker bloed in mijn u...,0,0_bloed_ontlasting_prikken_laten,"['bloed', 'ontlasting', 'prikken', 'laten', 'b...",['ik heb ongeveer 2 weken geleden bloed laten...,bloed - ontlasting - prikken - laten - bloed l...,1.000000,False
42534,Wat adviseert u hiermee te doen?,8,8_advies_probleem_graag advies_zorgen,"['advies', 'probleem', 'graag advies', 'zorgen...","['Graag jullie advies.', 'Wil graag advies', '...",advies - probleem - graag advies - zorgen - zi...,1.000000,False
42535,"Oke, dat is iig al een geruststelling ;) ik wa...",-1,-1_bedankt_dank_hoor_reactie,"['bedankt', 'dank', 'hoor', 'reactie', 'graag'...","['Alvast bedankt voor jullie reactie.', 'Alvas...",bedankt - dank - hoor - reactie - graag - hoor...,0.984811,False
42536,Dankjewel voor de snelle reactie!,-1,-1_bedankt_dank_hoor_reactie,"['bedankt', 'dank', 'hoor', 'reactie', 'graag'...","['Alvast bedankt voor jullie reactie.', 'Alvas...",bedankt - dank - hoor - reactie - graag - hoor...,0.861606,False

In [30]:
merged_df = pd.concat(
    [doc_info.set_index("Document")[["Topic"]],
     doc_info_merged.set_index("Document")[["Topic"]]],
    axis=1
).reset_index()

merged_df.columns = ["Document", "Topic_doc_info", "Topic_doc_info_merged"]

In [31]:
merged_df

,Document,Topic_doc_info,Topic_doc_info_merged
0,Ik ben 2 weken geleden met spoed opgenomen in ...,8,4
1,"Ik kreeg acuut een pijnlijke druk op de borst,...",271,2
2,Het begon 1 uur na het avondeten.,27,2
3,"Ik had al de hele dag migraine, had dus ook we...",78,1
4,"Ik werd heel erg misselijk, braakneigingen, du...",3,2
...,...,...,...
42532,"Ze hebben de urine op kweek gezet, kan morgenv...",0,0
42533,Afgelopen jaren is er al vaker bloed in mijn u...,0,0
42534,Wat adviseert u hiermee te doen?,253,8
42535,"Oke, dat is iig al een geruststelling ;) ik wa...",11,-1
42536,Dankjewel voor de snelle reactie!,105,-1

In [37]:
# Group by 'Topic_doc_info_merged' and list the corresponding 'Topic_doc_info' values
subgroups = (
    merged_df.groupby("Topic_doc_info_merged")["Topic_doc_info"]
    .apply(set)
    .reset_index()
)

# Rename columns for clarity
subgroups.columns = ["Topic_doc_info_merged", "Topic_doc_info_group"]

In [38]:
pd.set_option('colwidth', 500)
subgroups

,Topic_doc_info_merged,Topic_doc_info_group
0,-1,"{10, 11, 21, 23, 25, 39, 42, 51, 53, 55, 62, 63, 69, 76, 82, 84, 85, 86, 89, 92, 94, 95, 98, 102, 103, 105, 109, 110, 111, 120, 122, 124, 127, 128, 129, 130, 131, 135, 137, 141, 145, 146, 148, 153, 157, 159, 160, 161, 165, 171, 179, 187, 188, 195, 198, 201, 205, 208, 212, 214, 215, 216, 219, 222, 226, 227, 228, 229, 233, 234, 235, 237, 242, 245, 246, 247, 248, 249, 250, 252, 258, 263, 265, 266, 267, 268, 269, 270, 273, 279, 282, 284, 285, 287, -1}"
1,0,"{0, 2, 163, 231, 169, 75, 44, 142, 46, 80, 50, 243, 158, 223}"
2,1,"{1, 132, 134, 140, 14, 16, 147, 149, 278, 280, 283, 31, 33, 164, 167, 177, 180, 56, 185, 186, 74, 78, 79, 206, 83, 218, 96, 106, 125, 254}"
3,2,"{3, 264, 139, 271, 274, 24, 26, 27, 35, 168, 170, 45, 173, 178, 58, 59, 191, 65, 68, 87, 88, 91, 220, 221, 224, 97, 101, 112, 115, 118, 119, 121}"
4,3,"{256, 5, 133, 262, 261, 13, 272, 275, 276, 277, 28, 156, 286, 288, 43, 174, 176, 48, 52, 61, 189, 196, 70, 71, 72, 202, 203, 204, 230, 107, 108, 244, 126}"
5,4,"{7, 8, 73, 41, 12, 175, 18, 211, 20, 54, 182, 29, 190}"
6,5,"{64, 162, 194, 6, 166, 200, 199, 15, 143, 207, 117, 22, 151, 184, 281}"
7,6,"{138, 144, 155, 32, 34, 47, 57, 60, 192, 66, 67, 209, 210, 213, 217, 100, 238, 114, 251}"
8,7,"{4, 172, 81, 49, 17, 30}"
9,8,"{257, 99, 259, 37, 197, 90, 236, 77, 239, 150, 253, 154, 93, 255}"
10,9,"{193, 225, 38, 240, 113, 116, 183}"
11,10,"{136, 9, 104, 181}"
12,11,"{36, 260, 40, 232, 123}"
13,12,{19}
14,13,{152}
15,14,{241}