# SBERT Sentence Analysis

## 1. Preparations

### 1.1 Read Data
This new data is obtained after some further anonymization, and by putting previously incorrectly split sentences together, and removed duplicates

In [1]:
import pandas as pd
# read the sentence data 
df = pd.read_excel("/workspace/persistent/mijnidbcoachnlp/data/analysis_data/sentence_data_for_analysis.xlsx", index_col=0)
# check the df head
df.head()

,message_id,sentence,clean_sentence,sentence_id,translated_sentence
0,1,"Geachte ibd groep, Is mijn uitslag al binnen ...","ibd groep, Is mijn uitslag al binnen van de b...",1,"Dear Ibd group, has my results come back from ..."
1,3,Vorige week is door [ZIEKENHUIS] [LOCATIE] mij...,Vorige week is door mijn ontlasting onderzoc...,2,Last week my stool was examined by [SIGHSHOUSE...
2,3,Graag zou ik de uitkomst hiervan vernemen.,Graag zou ik de uitkomst hiervan vernemen.,3,I would like to hear the outcome of this.
3,4,bloed in de ontlasting wordt steeds meer en st...,bloed in de ontlasting wordt steeds meer en st...,4,blood in the stool is becoming more and more f...
4,4,Ligt dit aan de medicatie?,Ligt dit aan de medicatie?,5,Is this because of the medication?

In [2]:
# clean sentences as inputs
sentences = df["sentence"].to_list()
#clean_sentences = df["clean_sentence"].to_list()

In [ ]:
# print the size of the data
len(clean_sentences)
# There are 41119 sentences

41119

### 1.2. Import the list of stopwords

In [3]:
### Importing the list of Dutch stopwords (note that there are customized dutch words in there)

with open('/workspace/persistent/mijnidbcoachnlp/data/analysis_data/stopwords.txt', 'r') as file:
    lines = [line.strip() for line in file.readlines()]

dutch_stopwords = lines

In [4]:
# Extend the stop words if needed
extra_list = [
    'maandag', 'dinsdag', 'woensdag', 'donderdag', 'vrijdag', 'zaterdag', 'zondag',
    'januari', 'februari', 'maart', 'april', 'mei', 'juni', 'juli', 'augustus', 'september', 'oktober', 'november', 'december',
    'jan', 'feb', 'mrt', 'apr', 'mei', 'jun', 'jul', 'aug', 'sep', 'okt', 'nov', 'dec', "jl", "weken", "week", "dagen", "dag", "mg", "coach", "mijnibdcoach", "dr", "uur", "dgs"
]

dutch_stopwords.extend(extra_list)

### 1.4. Embed the lists of sentences

In [20]:
from sentence_transformers import SentenceTransformer
from tqdm import tqdm  # <-- Use the regular tqdm, not autonotebook
import numpy as np
import sentence_transformers.util
sentence_transformers.util.tqdm = tqdm

#### 1.4.1. sentence-transformers/distiluse-base-multilingual-cased-v1

In [ ]:
# Now use your model
embedding_model = SentenceTransformer("distiluse-base-multilingual-cased-v1")
# Generate and save embeddings
embeddings = embedding_model.encode(sentences, show_progress_bar=True)

In [ ]:
np.save('/workspace/persistent/mijnidbcoachnlp/data/embeddings/embeddings_st_v1_sentence_placeholder.npy', embeddings)

#### 1.4.2. sentence-transformers/distiluse-base-multilingual-cased-v2

In [ ]:
# Now use your model
embedding_model = SentenceTransformer("distiluse-base-multilingual-cased-v2")
# Generate and save embeddings
embeddings = embedding_model.encode(sentences, show_progress_bar=True)

In [23]:
np.save('/workspace/persistent/mijnidbcoachnlp/data/embeddings/embeddings_st_v2_sentence_placeholder.npy', embeddings)

#### 1.4.3. NetherlandsForensicInstitute/robbert-2022-dutch-sentence-transformers

In [ ]:
# Now use your model
embedding_model = SentenceTransformer("NetherlandsForensicInstitute/robbert-2022-dutch-sentence-transformers")
# Generate and save embeddings
embeddings = embedding_model.encode(sentences, show_progress_bar=True)

In [25]:
np.save('/workspace/persistent/mijnidbcoachnlp/data/embeddings/embeddings_st_robbert2022_sentence_placeholder.npy', embeddings)

#### 1.4.4. sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2

In [ ]:
# Now use your model
embedding_model = SentenceTransformer("sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2")
# Generate and save embeddings
embeddings = embedding_model.encode(sentences, show_progress_bar=True)

In [27]:
np.save('/workspace/persistent/mijnidbcoachnlp/data/embeddings/embeddings_st_miniL12v2_sentence_placeholder.npy', embeddings)

#### 1.4.5. sentence-transformers/paraphrase-multilingual-mpnet-base-v2

In [ ]:
# Now use your model
embedding_model = SentenceTransformer("sentence-transformers/paraphrase-multilingual-mpnet-base-v2")
# Generate and save embeddings
embeddings = embedding_model.encode(sentences, show_progress_bar=True)

In [29]:
np.save('/workspace/persistent/mijnidbcoachnlp/data/embeddings/embeddings_st_mpnet_v2_sentence_placeholder.npy', embeddings)

### 1.5. Tokenize the documents & define function for evaluation

In [14]:
# to calculate c_v, we need to import the original messages as the reference corpus
messages_df = pd.read_excel("/workspace/persistent/mijnidbcoachnlp/data/analysis_data/translated_clean_message_data.xlsx", index_col=0)
messages_df.head()

,provider_name,program_name,user_guid,date_time,message,direction,sender,message_id,clean_message,clean_message_stripped,translated_message
0,MUMC MijnIBDcoach,MijnIBDcoach,5422E6C6-75E8-4DAE-A6B6-E5EF46E2442E,2014-09-23 12:26:59.407,"Geachte ibd groep, Is mijn uitslag al binnen ...",From client,NaN,1,"Geachte ibd groep, Is mijn uitslag al binnen ...","ibd groep, Is mijn uitslag al binnen van de b...","Dear Ibd group, Is my rash already in from las..."
1,MUMC MijnIBDcoach,MijnIBDcoach,5422E6C6-75E8-4DAE-A6B6-E5EF46E2442E,2014-09-24 14:44:58.373,"Beste [PERSOON-1], Zojuist zag ik de uitslag ...",To client,mjong_mumc,2,"Beste [PERSOON], Zojuist zag ik de uitslag va...","Zojuist zag ik de uitslag van de botscan, de b...","Dear [PERSOON], I just saw the results of the ..."
2,MUMC MijnIBDcoach,MijnIBDcoach,12E3C542-9F96-43A4-BEE9-06225FEE170A,2014-09-27 07:46:52.670,Hallo! Vorige week is door [ZIEKENHUIS-1] [LOC...,From client,NaN,3,Hallo! Vorige week is door [ZIEKENHUIS] [LOCAT...,Vorige week is door mijn ontlasting onderzoc...,Hello! Last week my stool was examined by [LOC...
3,MUMC MijnIBDcoach,MijnIBDcoach,70E019C6-0F45-46D3-ADBF-16AD727C8EA0,2014-09-28 09:42:34.670,bloed in de ontlasting wordt steeds meer en st...,From client,NaN,4,bloed in de ontlasting wordt steeds meer en st...,bloed in de ontlasting wordt steeds meer en st...,blood in the stool is becoming more and more f...
4,MUMC MijnIBDcoach,MijnIBDcoach,70E019C6-0F45-46D3-ADBF-16AD727C8EA0,2014-09-29 10:08:41.710,"Beste [PERSOON-1], haaruitval kan te maken heb...",To client,htomlow_mumc,5,"Beste [PERSOON], haaruitval kan te maken hebbe...",haaruitval kan te maken hebben met medicatiege...,"Dear [PERSOON], hair loss may be related to me..."

In [15]:
messages = messages_df["clean_message"].to_list()
len(messages)

32681

In [5]:
# download nltk and spacy library
import spacy
import nltk
from nltk.tokenize import word_tokenize

# Download NLTK's tokenizer (only needed once)
nltk.download("punkt")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [17]:
#tokenize the texts with nltk
tokenized_texts_nltk = [word_tokenize(message, language="dutch") for message in messages]
tokenized_texts = tokenized_texts_nltk

In [10]:
from gensim.models.coherencemodel import CoherenceModel
from gensim.corpora.dictionary import Dictionary
from octis.evaluation_metrics.diversity_metrics import TopicDiversity
from octis.evaluation_metrics.coherence_metrics import Coherence

# Create a dictionary representation of the words in topics
dictionary = Dictionary(tokenized_texts)

def get_top_words(topic_model):
    topics = topic_model.get_topics()
    top_words = [[word for word, _ in topic[:10]] for topic in topics.values() if topic]  # Top 10 words per topic
    return top_words

def calculate_c_v(topic_model):
    top_words = get_top_words(topic_model)
    coherence_model = CoherenceModel(topics=top_words, 
                                texts=tokenized_texts,
                                dictionary=dictionary, 
                                coherence='c_v')
    coherence_score = coherence_model.get_coherence()
    return coherence_score

def get_npmi(text, topics):

    return npmi

def get_silhouette_score(topic_model):

In [8]:
# disable parallelism to avoid some warnings
import os
os.environ["TOKENIZERS_PARALLELISM"] = "false"

## 2. Fit a BERTopic model

In [9]:
import numpy as np
embeddings_stv1 = np.load("/workspace/persistent/mijnidbcoachnlp/data/embeddings/embeddings_st_v1_sentence_placeholder.npy")
embeddings_stv2 = np.load("/workspace/persistent/mijnidbcoachnlp/data/embeddings/embeddings_st_v1_sentence_placeholder.npy")
embeddings_stmini = np.load("/workspace/persistent/mijnidbcoachnlp/data/embeddings/embeddings_st_miniL12v2_sentence_placeholder.npy")
embeddings_stmp = np.load("/workspace/persistent/mijnidbcoachnlp/data/embeddings/embeddings_st_mpnet_v2_sentence_placeholder.npy")
embeddings_strob = np.load("/workspace/persistent/mijnidbcoachnlp/data/embeddings/embeddings_st_robbert2022_sentence_placeholder.npy")

### 2.1 Initialize a BERTopic model with default configurations

In [12]:
from copy import deepcopy
from umap import UMAP
from hdbscan import HDBSCAN
from sklearn.feature_extraction.text import CountVectorizer

# Shared settings (avoid code duplication)
bertopic_settings = {
    "umap_model": UMAP(n_neighbors=15, n_components=5, min_dist=0.0, metric='cosine', random_state=42),
    "hdbscan_model": HDBSCAN(min_cluster_size=15, metric='euclidean', cluster_selection_method='eom', prediction_data=False),
    "vectorizer_model": CountVectorizer(stop_words=dutch_stopwords, min_df=2, ngram_range=(1, 1), token_pattern=r'\b[a-zA-Z]{3,}\b'),
    "calculate_probabilities": False
}

In [ ]:
# Store results for each embedding
results = {}

for name, embeddings in [("stv1", embeddings_stv1), ("stv2", embeddings_stv2), ("mini", embeddings_stmini), ("mpnet", embeddings_stmp), ("robbert", embeddings_strob)]:
    # Create a new instance per embedding
    topic_model = BERTopic(**bertopic_settings)
    topics, probs = topic_model.fit_transform(sentences, embeddings=embeddings)
    cv = calculate_c_v(topic_model=topic_model)
    silhouette = 
    outlier_ratio = 
    # Save everything (including the model if needed)
    results[name] = {
        "topics": topics,
        "model": deepcopy(topic_model),  # Preserve state
        "c_v score": cv,
        "silhouette": sil_score
    }

### 2.2 Trying different embedding models

#### 2.2.1. ST multilingual cased v1

In [48]:
topics, probs = topic_model.fit_transform(sentences, embeddings=embeddings_stv1) # here the default settings of BERTopic is used, with embedding model ST all-MiniLM-L6-v2

In [49]:
# print out the topic info
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,17404,-1_afspraak_gaat_last_klachten,"[afspraak, gaat, last, klachten, krijg, contac...","[Goedemorgen, Misschien een stomme vraag over..."
1,0,3422,0_bloed_prikken_bloedprikken_slijm,"[bloed, prikken, bloedprikken, slijm, ontlasti...",[Ik zal in februari van 2018 mijn bloed laten ...
2,1,464,1_medicatie_medicijnen_apotheek_medicijn,"[medicatie, medicijnen, apotheek, medicijn, re...","[Mag niet kagen, en dat zonder medicatie., Mij..."
3,2,385,2_pijn_buikpijn_pijnlijk_pijnlijke,"[pijn, buikpijn, pijnlijk, pijnlijke, spierpij...","[Maar ik heb af en toe meer pijn., Geen pijn m..."
4,3,374,3_vraag_vragen_vragenlijst_vraagje,"[vraag, vragen, vragenlijst, vraagje, vraagjes...","[Ik heb wel nog een vraag., Ik heb nog een vra..."
...,...,...,...,...,...
326,325,15,325_tabletten_tablet_bisacodyl_mezavant,"[tabletten, tablet, bisacodyl, mezavant, innem...",[In de bijgevoegde info lees ik dat je de dag ...
327,326,15,326_maand_maanden_herken_opzwelling,"[maand, maanden, herken, opzwelling, voorhoofd...","[Beste, Ik heb al een aantal maanden last van..."
328,327,15,327_antibiotica_probiotica_aangemaakte_indertijd,"[antibiotica, probiotica, aangemaakte, inderti...",[Is probiotica nodig of helpzaam tegen klachte...
329,328,15,328_ene_cyclus_anderen_achtergrond,"[ene, cyclus, anderen, achtergrond, namen, geh...","[de ene dag meer last dan de andere., Het is d..."
330,329,15,329_verpleegkundige_ibd_artsen_infectie,"[verpleegkundige, ibd, artsen, infectie, urine...","[Beste IBD Verpleegkundige, Zoals beloofd heb..."

In [50]:
calculate_c_v(topic_model)

0.34452348750545536

#### 2.2.2. ST multilingual V2

In [51]:
topics, probs = topic_model.fit_transform(sentences, embeddings=embeddings_stv2) # here the default settings of BERTopic is used, with embedding model ST all-MiniLM-L6-v2

In [52]:
# print out the topic info
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,16972,-1_afspraak_last_gaat_klachten,"[afspraak, last, gaat, klachten, contact, poli...",[Ik heb al een mail gekregen dat ik een poli-a...
1,0,3368,0_bloed_prikken_bloedprikken_slijm,"[bloed, prikken, bloedprikken, slijm, ontlasti...","[Hallo, ik heb het bloed laten prikken in [LOC..."
2,1,785,1_test_testen_proberen_quanton,"[test, testen, proberen, quanton, cal, zelftes...","[Wanneer moet ik z’n test doen?, Ook de test v..."
3,2,498,2_medicatie_medicijnen_apotheek_medicijn,"[medicatie, medicijnen, apotheek, medicijn, re...",[Nu is het recept nog niet binnen bij de apoth...
4,3,400,3_vraag_vragen_vraagje_vragenlijst,"[vraag, vragen, vraagje, vragenlijst, vraagjes...","[Ik heb wel nog een vraag., Ik heb een vraag.,..."
...,...,...,...,...,...
312,311,16,311_hulp_sittard_wijzer_verwisseld,"[hulp, sittard, wijzer, verwisseld, moeizamer,...","[Dit is goed gegaan de eerste keer, ik ben wij..."
313,312,16,312_ziekte_bechterew_vastgesteld_diagnose,"[ziekte, bechterew, vastgesteld, diagnose, wer...",[Is dit normaal voor de ziekte van bechterew n...
314,313,16,313_gaten_houden_container_nauwlettend,"[gaten, houden, container, nauwlettend, meebre...","[Ik zal het in de gaten houden., Ik zal het in..."
315,314,15,314_reactie_bedankt_hallo_dankjewel,"[reactie, bedankt, hallo, dankjewel, toesturen...","[Hallo [PERSOON], Bedankt voor u reactie., Ha..."
316,315,15,315_prima_helemaal_psyllium_vooruitgang,"[prima, helemaal, psyllium, vooruitgang, orde,...","[Dat is helemaal prima., Dat is helemaal prima..."

In [54]:
# Initialize BERTopic
topic_model = BERTopic(
    umap_model=UMAP(n_neighbors=15, n_components=5, min_dist=0.0, metric='cosine', ),
    hdbscan_model=HDBSCAN(min_cluster_size=15, metric='euclidean', cluster_selection_method='eom', prediction_data=False),
    vectorizer_model=CountVectorizer(stop_words=dutch_stopwords, min_df=2, ngram_range=(1, 1), token_pattern=r'\b[a-zA-Z]{3,}\b'), #ngram must be (1,1) for c_v calculation
    calculate_probabilities=False
)
topics, probs = topic_model.fit_transform(sentences, embeddings=embeddings_stv2) # here the default settings of BERTopic is used, with embedding model ST all-MiniLM-L6-v2

In [55]:
# print out the topic info
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,17041,-1_afspraak_last_vragen_gaat,"[afspraak, last, vragen, gaat, vraag, klachten...","[Goede middag, ja had graag recept thuis omdat..."
1,0,3383,0_bloed_prikken_bloedprikken_slijm,"[bloed, prikken, bloedprikken, slijm, ontlasti...","[Ok, dan ga ik deze week nog bloed laten prikk..."
2,1,780,1_test_testen_proberen_quanton,"[test, testen, proberen, quanton, zelftest, ca...","[Zal de test doen., De test was echter nog nie..."
3,2,436,2_medicatie_medicijnen_apotheek_medicijn,"[medicatie, medicijnen, apotheek, medicijn, re...",[Nu is het recept nog niet binnen bij de apoth...
4,3,422,3_arts_huisarts_mdl_contact,"[arts, huisarts, mdl, contact, dokter, special...","[Mijn eigen arts was er niet., Ik ben laatst b..."
...,...,...,...,...,...
323,322,16,322_nieuws_fantastisch_super_goed,"[nieuws, fantastisch, super, goed, helaas, uit...","[Dat is heel goed nieuws!, Dus goed nieuws., N..."
324,323,16,323_reactie_uitsluiten_dankjewel_hallo,"[reactie, uitsluiten, dankjewel, hallo, bedank...","[Hallo [PERSOON], Bedankt voor je reactie., Ha..."
325,324,15,324_afwachten_wachten_overgaat_dalen,"[afwachten, wachten, overgaat, dalen, vanzelf,...","[Moet ik dat afwachten?, Zullen we dit dan nog..."
326,325,15,325_asmaandag_wetenschappelijk_hum_gemakkelijk,"[asmaandag, wetenschappelijk, hum, gemakkelijk...","[Beste [PERSOON], Ik heb 2 februari a.s. 14:30..."
327,326,15,326_verwachting_verwacht_wacht_bricht,"[verwachting, verwacht, wacht, bricht, ontdekk...",[Ik verwacht nog daar bricht over te krijgen.....